// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// ForgetPasswordOKCode is the HTTP code returned for type ForgetPasswordOK
const ForgetPasswordOKCode int = 200

/*
ForgetPasswordOK Reset link sent (if email exists)

swagger:response forgetPasswordOK
*/
type ForgetPasswordOK struct {

	/*
	  In: Body
	*/
	Payload *ForgetPasswordOKBody `json:"body,omitempty"`
}

// NewForgetPasswordOK creates ForgetPasswordOK with default headers values
func NewForgetPasswordOK() *ForgetPasswordOK {

	return &ForgetPasswordOK{}
}

// WithPayload adds the payload to the forget password o k response
func (o *ForgetPasswordOK) WithPayload(payload *ForgetPasswordOKBody) *ForgetPasswordOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the forget password o k response
func (o *ForgetPasswordOK) SetPayload(payload *ForgetPasswordOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ForgetPasswordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ForgetPasswordBadRequestCode is the HTTP code returned for type ForgetPasswordBadRequest
const ForgetPasswordBadRequestCode int = 400

/*
ForgetPasswordBadRequest Invalid refresh token

swagger:response forgetPasswordBadRequest
*/
type ForgetPasswordBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewForgetPasswordBadRequest creates ForgetPasswordBadRequest with default headers values
func NewForgetPasswordBadRequest() *ForgetPasswordBadRequest {

	return &ForgetPasswordBadRequest{}
}

// WithPayload adds the payload to the forget password bad request response
func (o *ForgetPasswordBadRequest) WithPayload(payload *models.ErrorResponse) *ForgetPasswordBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the forget password bad request response
func (o *ForgetPasswordBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ForgetPasswordBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
