// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ForgetPasswordHandlerFunc turns a function with the right signature into a forget password handler
type ForgetPasswordHandlerFunc func(ForgetPasswordParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ForgetPasswordHandlerFunc) Handle(params ForgetPasswordParams) middleware.Responder {
	return fn(params)
}

// ForgetPasswordHandler interface for that can handle valid forget password params
type ForgetPasswordHandler interface {
	Handle(ForgetPasswordParams) middleware.Responder
}

// NewForgetPassword creates a new http.Handler for the forget password operation
func NewForgetPassword(ctx *middleware.Context, handler ForgetPasswordHandler) *ForgetPassword {
	return &ForgetPassword{Context: ctx, Handler: handler}
}

/*
	ForgetPassword swagger:route POST /auth/forgot-password Users forgetPassword

# Request password reset

Sends a reset password link to the user's email
*/
type ForgetPassword struct {
	Context *middleware.Context
	Handler ForgetPasswordHandler
}

func (o *ForgetPassword) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewForgetPasswordParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ForgetPasswordBody forget password body
//
// swagger:model ForgetPasswordBody
type ForgetPasswordBody struct {

	// email
	// Example: user@example.com
	// Required: true
	Email *string `json:"email"`
}

// Validate validates this forget password body
func (o *ForgetPasswordBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ForgetPasswordBody) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"email", "body", o.Email); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this forget password body based on context it is used
func (o *ForgetPasswordBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ForgetPasswordBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ForgetPasswordBody) UnmarshalBinary(b []byte) error {
	var res ForgetPasswordBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// ForgetPasswordOKBody forget password o k body
//
// swagger:model ForgetPasswordOKBody
type ForgetPasswordOKBody struct {

	// message
	// Example: If the email exists, a reset link has been sent
	Message string `json:"message,omitempty"`
}

// Validate validates this forget password o k body
func (o *ForgetPasswordOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this forget password o k body based on context it is used
func (o *ForgetPasswordOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ForgetPasswordOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ForgetPasswordOKBody) UnmarshalBinary(b []byte) error {
	var res ForgetPasswordOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
