// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// GetUserProfileOKCode is the HTTP code returned for type GetUserProfileOK
const GetUserProfileOKCode int = 200

/*
GetUserProfileOK User profile details

swagger:response getUserProfileOK
*/
type GetUserProfileOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewGetUserProfileOK creates GetUserProfileOK with default headers values
func NewGetUserProfileOK() *GetUserProfileOK {

	return &GetUserProfileOK{}
}

// WithPayload adds the payload to the get user profile o k response
func (o *GetUserProfileOK) WithPayload(payload *models.User) *GetUserProfileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user profile o k response
func (o *GetUserProfileOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUserProfileUnauthorizedCode is the HTTP code returned for type GetUserProfileUnauthorized
const GetUserProfileUnauthorizedCode int = 401

/*
GetUserProfileUnauthorized Unauthorized

swagger:response getUserProfileUnauthorized
*/
type GetUserProfileUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetUserProfileUnauthorized creates GetUserProfileUnauthorized with default headers values
func NewGetUserProfileUnauthorized() *GetUserProfileUnauthorized {

	return &GetUserProfileUnauthorized{}
}

// WithPayload adds the payload to the get user profile unauthorized response
func (o *GetUserProfileUnauthorized) WithPayload(payload *models.ErrorResponse) *GetUserProfileUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user profile unauthorized response
func (o *GetUserProfileUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserProfileUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
