// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IdentifyUserHandlerFunc turns a function with the right signature into a identify user handler
type IdentifyUserHandlerFunc func(IdentifyUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn IdentifyUserHandlerFunc) Handle(params IdentifyUserParams) middleware.Responder {
	return fn(params)
}

// IdentifyUserHandler interface for that can handle valid identify user params
type IdentifyUserHandler interface {
	Handle(IdentifyUserParams) middleware.Responder
}

// NewIdentifyUser creates a new http.Handler for the identify user operation
func NewIdentifyUser(ctx *middleware.Context, handler IdentifyUserHandler) *IdentifyUser {
	return &IdentifyUser{Context: ctx, Handler: handler}
}

/*
	IdentifyUser swagger:route POST /auth/identify Users identifyUser

# Identify user by email or phone

Determines whether a user exists and their verification status
*/
type IdentifyUser struct {
	Context *middleware.Context
	Handler IdentifyUserHandler
}

func (o *IdentifyUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewIdentifyUserParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// IdentifyUserBody identify user body
//
// swagger:model IdentifyUserBody
type IdentifyUserBody struct {

	// identifier
	// Example: user@example.com
	// Required: true
	Identifier *string `json:"identifier"`
}

// Validate validates this identify user body
func (o *IdentifyUserBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateIdentifier(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *IdentifyUserBody) validateIdentifier(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"identifier", "body", o.Identifier); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this identify user body based on context it is used
func (o *IdentifyUserBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *IdentifyUserBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *IdentifyUserBody) UnmarshalBinary(b []byte) error {
	var res IdentifyUserBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
