// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// LogoutUserOKCode is the HTTP code returned for type LogoutUserOK
const LogoutUserOKCode int = 200

/*
LogoutUserOK Logout successful

swagger:response logoutUserOK
*/
type LogoutUserOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewLogoutUserOK creates LogoutUserOK with default headers values
func NewLogoutUserOK() *LogoutUserOK {

	return &LogoutUserOK{}
}

// WithPayload adds the payload to the logout user o k response
func (o *LogoutUserOK) WithPayload(payload *models.SuccessResponse) *LogoutUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the logout user o k response
func (o *LogoutUserOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogoutUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// LogoutUserUnauthorizedCode is the HTTP code returned for type LogoutUserUnauthorized
const LogoutUserUnauthorizedCode int = 401

/*
LogoutUserUnauthorized Unauthorized

swagger:response logoutUserUnauthorized
*/
type LogoutUserUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewLogoutUserUnauthorized creates LogoutUserUnauthorized with default headers values
func NewLogoutUserUnauthorized() *LogoutUserUnauthorized {

	return &LogoutUserUnauthorized{}
}

// WithPayload adds the payload to the logout user unauthorized response
func (o *LogoutUserUnauthorized) WithPayload(payload *models.ErrorResponse) *LogoutUserUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the logout user unauthorized response
func (o *LogoutUserUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogoutUserUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
