// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// OTPLoginHandlerFunc turns a function with the right signature into a o t p login handler
type OTPLoginHandlerFunc func(OTPLoginParams) middleware.Responder

// Handle executing the request and returning a response
func (fn OTPLoginHandlerFunc) Handle(params OTPLoginParams) middleware.Responder {
	return fn(params)
}

// OTPLoginHandler interface for that can handle valid o t p login params
type OTPLoginHandler interface {
	Handle(OTPLoginParams) middleware.Responder
}

// NewOTPLogin creates a new http.Handler for the o t p login operation
func NewOTPLogin(ctx *middleware.Context, handler OTPLoginHandler) *OTPLogin {
	return &OTPLogin{Context: ctx, Handler: handler}
}

/*
	OTPLogin swagger:route POST /auth/otp/send Users oTPLogin

Send OTP to email or phone
*/
type OTPLogin struct {
	Context *middleware.Context
	Handler OTPLoginHandler
}

func (o *OTPLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewOTPLoginParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
