// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostAuthOtpResendHandlerFunc turns a function with the right signature into a post auth otp resend handler
type PostAuthOtpResendHandlerFunc func(PostAuthOtpResendParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAuthOtpResendHandlerFunc) Handle(params PostAuthOtpResendParams) middleware.Responder {
	return fn(params)
}

// PostAuthOtpResendHandler interface for that can handle valid post auth otp resend params
type PostAuthOtpResendHandler interface {
	Handle(PostAuthOtpResendParams) middleware.Responder
}

// NewPostAuthOtpResend creates a new http.Handler for the post auth otp resend operation
func NewPostAuthOtpResend(ctx *middleware.Context, handler PostAuthOtpResendHandler) *PostAuthOtpResend {
	return &PostAuthOtpResend{Context: ctx, Handler: handler}
}

/*
	PostAuthOtpResend swagger:route POST /auth/otp/resend Users postAuthOtpResend

Resend OTP
*/
type PostAuthOtpResend struct {
	Context *middleware.Context
	Handler PostAuthOtpResendHandler
}

func (o *PostAuthOtpResend) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAuthOtpResendParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
