// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAuthOtpResendOKCode is the HTTP code returned for type PostAuthOtpResendOK
const PostAuthOtpResendOKCode int = 200

/*
PostAuthOtpResendOK OTP resent

swagger:response postAuthOtpResendOK
*/
type PostAuthOtpResendOK struct {
}

// NewPostAuthOtpResendOK creates PostAuthOtpResendOK with default headers values
func NewPostAuthOtpResendOK() *PostAuthOtpResendOK {

	return &PostAuthOtpResendOK{}
}

// WriteResponse to the client
func (o *PostAuthOtpResendOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
