// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// RegisterUserCreatedCode is the HTTP code returned for type RegisterUserCreated
const RegisterUserCreatedCode int = 201

/*
RegisterUserCreated User registered successfully

swagger:response registerUserCreated
*/
type RegisterUserCreated struct {

	/*
	  In: Body
	*/
	Payload *models.AuthResponse `json:"body,omitempty"`
}

// NewRegisterUserCreated creates RegisterUserCreated with default headers values
func NewRegisterUserCreated() *RegisterUserCreated {

	return &RegisterUserCreated{}
}

// WithPayload adds the payload to the register user created response
func (o *RegisterUserCreated) WithPayload(payload *models.AuthResponse) *RegisterUserCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register user created response
func (o *RegisterUserCreated) SetPayload(payload *models.AuthResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterUserCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterUserBadRequestCode is the HTTP code returned for type RegisterUserBadRequest
const RegisterUserBadRequestCode int = 400

/*
RegisterUserBadRequest Validation error

swagger:response registerUserBadRequest
*/
type RegisterUserBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewRegisterUserBadRequest creates RegisterUserBadRequest with default headers values
func NewRegisterUserBadRequest() *RegisterUserBadRequest {

	return &RegisterUserBadRequest{}
}

// WithPayload adds the payload to the register user bad request response
func (o *RegisterUserBadRequest) WithPayload(payload *models.ErrorResponse) *RegisterUserBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register user bad request response
func (o *RegisterUserBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterUserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
