// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// RequestPasswordResetOKCode is the HTTP code returned for type RequestPasswordResetOK
const RequestPasswordResetOKCode int = 200

/*
RequestPasswordResetOK Password reset email sent

swagger:response requestPasswordResetOK
*/
type RequestPasswordResetOK struct {
}

// NewRequestPasswordResetOK creates RequestPasswordResetOK with default headers values
func NewRequestPasswordResetOK() *RequestPasswordResetOK {

	return &RequestPasswordResetOK{}
}

// WriteResponse to the client
func (o *RequestPasswordResetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// RequestPasswordResetBadRequestCode is the HTTP code returned for type RequestPasswordResetBadRequest
const RequestPasswordResetBadRequestCode int = 400

/*
RequestPasswordResetBadRequest Invalid email

swagger:response requestPasswordResetBadRequest
*/
type RequestPasswordResetBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewRequestPasswordResetBadRequest creates RequestPasswordResetBadRequest with default headers values
func NewRequestPasswordResetBadRequest() *RequestPasswordResetBadRequest {

	return &RequestPasswordResetBadRequest{}
}

// WithPayload adds the payload to the request password reset bad request response
func (o *RequestPasswordResetBadRequest) WithPayload(payload *models.ErrorResponse) *RequestPasswordResetBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the request password reset bad request response
func (o *RequestPasswordResetBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RequestPasswordResetBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
