// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RequestPasswordResetHandlerFunc turns a function with the right signature into a request password reset handler
type RequestPasswordResetHandlerFunc func(RequestPasswordResetParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RequestPasswordResetHandlerFunc) Handle(params RequestPasswordResetParams) middleware.Responder {
	return fn(params)
}

// RequestPasswordResetHandler interface for that can handle valid request password reset params
type RequestPasswordResetHandler interface {
	Handle(RequestPasswordResetParams) middleware.Responder
}

// NewRequestPasswordReset creates a new http.Handler for the request password reset operation
func NewRequestPasswordReset(ctx *middleware.Context, handler RequestPasswordResetHandler) *RequestPasswordReset {
	return &RequestPasswordReset{Context: ctx, Handler: handler}
}

/*
	RequestPasswordReset swagger:route POST /auth/forgot-password Users requestPasswordReset

Request password reset
*/
type RequestPasswordReset struct {
	Context *middleware.Context
	Handler RequestPasswordResetHandler
}

func (o *RequestPasswordReset) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRequestPasswordResetParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
