// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// UpdateUserProfileOKCode is the HTTP code returned for type UpdateUserProfileOK
const UpdateUserProfileOKCode int = 200

/*
UpdateUserProfileOK Profile updated successfully

swagger:response updateUserProfileOK
*/
type UpdateUserProfileOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewUpdateUserProfileOK creates UpdateUserProfileOK with default headers values
func NewUpdateUserProfileOK() *UpdateUserProfileOK {

	return &UpdateUserProfileOK{}
}

// WithPayload adds the payload to the update user profile o k response
func (o *UpdateUserProfileOK) WithPayload(payload *models.User) *UpdateUserProfileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user profile o k response
func (o *UpdateUserProfileOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateUserProfileBadRequestCode is the HTTP code returned for type UpdateUserProfileBadRequest
const UpdateUserProfileBadRequestCode int = 400

/*
UpdateUserProfileBadRequest Validation error

swagger:response updateUserProfileBadRequest
*/
type UpdateUserProfileBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewUpdateUserProfileBadRequest creates UpdateUserProfileBadRequest with default headers values
func NewUpdateUserProfileBadRequest() *UpdateUserProfileBadRequest {

	return &UpdateUserProfileBadRequest{}
}

// WithPayload adds the payload to the update user profile bad request response
func (o *UpdateUserProfileBadRequest) WithPayload(payload *models.ErrorResponse) *UpdateUserProfileBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user profile bad request response
func (o *UpdateUserProfileBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserProfileBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateUserProfileUnauthorizedCode is the HTTP code returned for type UpdateUserProfileUnauthorized
const UpdateUserProfileUnauthorizedCode int = 401

/*
UpdateUserProfileUnauthorized Unauthorized

swagger:response updateUserProfileUnauthorized
*/
type UpdateUserProfileUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewUpdateUserProfileUnauthorized creates UpdateUserProfileUnauthorized with default headers values
func NewUpdateUserProfileUnauthorized() *UpdateUserProfileUnauthorized {

	return &UpdateUserProfileUnauthorized{}
}

// WithPayload adds the payload to the update user profile unauthorized response
func (o *UpdateUserProfileUnauthorized) WithPayload(payload *models.ErrorResponse) *UpdateUserProfileUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user profile unauthorized response
func (o *UpdateUserProfileUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserProfileUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
