// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// VerifyOTPHandlerFunc turns a function with the right signature into a verify o t p handler
type VerifyOTPHandlerFunc func(VerifyOTPParams) middleware.Responder

// Handle executing the request and returning a response
func (fn VerifyOTPHandlerFunc) Handle(params VerifyOTPParams) middleware.Responder {
	return fn(params)
}

// VerifyOTPHandler interface for that can handle valid verify o t p params
type VerifyOTPHandler interface {
	Handle(VerifyOTPParams) middleware.Responder
}

// NewVerifyOTP creates a new http.Handler for the verify o t p operation
func NewVerifyOTP(ctx *middleware.Context, handler VerifyOTPHandler) *VerifyOTP {
	return &VerifyOTP{Context: ctx, Handler: handler}
}

/*
	VerifyOTP swagger:route POST /auth/otp/verify Users verifyOTP

Verify OTP and login user
*/
type VerifyOTP struct {
	Context *middleware.Context
	Handler VerifyOTPHandler
}

func (o *VerifyOTP) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewVerifyOTPParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
