// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// VerifyOTPOKCode is the HTTP code returned for type VerifyOTPOK
const VerifyOTPOKCode int = 200

/*
VerifyOTPOK Successful login

swagger:response verifyOTPOK
*/
type VerifyOTPOK struct {
}

// NewVerifyOTPOK creates VerifyOTPOK with default headers values
func NewVerifyOTPOK() *VerifyOTPOK {

	return &VerifyOTPOK{}
}

// WriteResponse to the client
func (o *VerifyOTPOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// VerifyOTPUnauthorizedCode is the HTTP code returned for type VerifyOTPUnauthorized
const VerifyOTPUnauthorizedCode int = 401

/*
VerifyOTPUnauthorized Invalid OTP

swagger:response verifyOTPUnauthorized
*/
type VerifyOTPUnauthorized struct {
}

// NewVerifyOTPUnauthorized creates VerifyOTPUnauthorized with default headers values
func NewVerifyOTPUnauthorized() *VerifyOTPUnauthorized {

	return &VerifyOTPUnauthorized{}
}

// WriteResponse to the client
func (o *VerifyOTPUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
