// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Admin API
//
//	Admin APIs for managing products, users, orders, and payments.
//	Schemes:
//	  https
//	Host: api.adornme.com
//	BasePath: /v1/admin
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
