openapi: 3.0.3
info:
  title: Payment API
  version: 1.0.0
  description: |
    API specification for handling payments in the e-commerce system.
    Integrates with payment gateways (e.g., Stripe, Razorpay, PayPal, UPI).

servers:
  - url: https://api.adornme.com/v1
    description: Production server
  - url: https://staging-api.adornme.com/v1
    description: Staging server

tags:
  - name: Payments
    description: Payment initialization, confirmation, and tracking

paths:
  /payments/initiate:
    post:
      summary: Initiate a new payment
      tags: [Payments]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentInitiateRequest"
      responses:
        "201":
          description: Payment initiated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentInitiateResponse"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /payments/{id}:
    get:
      summary: Get payment details
      tags: [Payments]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Payment details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
        "404":
          description: Payment not found

  /payments/{id}/confirm:
    post:
      summary: Confirm a payment (callback from gateway)
      tags: [Payments]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentConfirmRequest"
      responses:
        "200":
          description: Payment confirmed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
        "400":
          description: Invalid confirmation data

  /payments/{id}/refund:
    post:
      summary: Refund a payment
      tags: [Payments]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefundRequest"
      responses:
        "200":
          description: Refund processed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
        "400":
          description: Invalid refund request
        "404":
          description: Payment not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Payment:
      type: object
      properties:
        id:
          type: string
          example: pay_abc123
        orderId:
          type: integer
          example: 5001
        userId:
          type: integer
          example: 101
        amount:
          type: number
          format: float
          example: 2999.50
        currency:
          type: string
          example: INR
        method:
          type: string
          enum: [card, netbanking, upi, wallet, paypal]
          example: upi
        status:
          type: string
          enum: [initiated, pending, success, failed, refunded]
          example: initiated
        transactionId:
          type: string
          example: txn_789xyz
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    PaymentInitiateRequest:
      type: object
      required: [orderId, method]
      properties:
        orderId:
          type: integer
          example: 5001
        method:
          type: string
          enum: [card, netbanking, upi, wallet, paypal]
          example: upi

    PaymentInitiateResponse:
      type: object
      properties:
        paymentId:
          type: string
          example: pay_abc123
        gatewayUrl:
          type: string
          format: uri
          example: https://razorpay.com/pay/xyz
        status:
          type: string
          enum: [initiated, pending]
          example: initiated

    PaymentConfirmRequest:
      type: object
      required: [transactionId, status]
      properties:
        transactionId:
          type: string
          example: txn_789xyz
        status:
          type: string
          enum: [success, failed]
          example: success
        signature:
          type: string
          description: Gateway signature for validation

    RefundRequest:
      type: object
      required: [amount, reason]
      properties:
        amount:
          type: number
          format: float
          example: 1499.75
        reason:
          type: string
          example: Customer requested refund

    ErrorResponse:
      type: object
      required: [error, message]
      properties:
        error:
          type: string
          example: BadRequest
        message:
          type: string
          example: Invalid payment method
