// Code generated by go-swagger; DO NOT EDIT.

package cart

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// AddItemToCartOKCode is the HTTP code returned for type AddItemToCartOK
const AddItemToCartOKCode int = 200

/*
AddItemToCartOK Item added to cart

swagger:response addItemToCartOK
*/
type AddItemToCartOK struct {

	/*
	  In: Body
	*/
	Payload *models.Cart `json:"body,omitempty"`
}

// NewAddItemToCartOK creates AddItemToCartOK with default headers values
func NewAddItemToCartOK() *AddItemToCartOK {

	return &AddItemToCartOK{}
}

// WithPayload adds the payload to the add item to cart o k response
func (o *AddItemToCartOK) WithPayload(payload *models.Cart) *AddItemToCartOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add item to cart o k response
func (o *AddItemToCartOK) SetPayload(payload *models.Cart) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddItemToCartOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
