// Code generated by go-swagger; DO NOT EDIT.

package cart

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"Adornme/models"
)

// AddItemToCartHandlerFunc turns a function with the right signature into a add item to cart handler
type AddItemToCartHandlerFunc func(AddItemToCartParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn AddItemToCartHandlerFunc) Handle(params AddItemToCartParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// AddItemToCartHandler interface for that can handle valid add item to cart params
type AddItemToCartHandler interface {
	Handle(AddItemToCartParams, *models.Principal) middleware.Responder
}

// NewAddItemToCart creates a new http.Handler for the add item to cart operation
func NewAddItemToCart(ctx *middleware.Context, handler AddItemToCartHandler) *AddItemToCart {
	return &AddItemToCart{Context: ctx, Handler: handler}
}

/*
	AddItemToCart swagger:route POST /cart Cart addItemToCart

Add item to cart
*/
type AddItemToCart struct {
	Context *middleware.Context
	Handler AddItemToCartHandler
}

func (o *AddItemToCart) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddItemToCartParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
