// Code generated by go-swagger; DO NOT EDIT.

package cart

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ClearCartNoContentCode is the HTTP code returned for type ClearCartNoContent
const ClearCartNoContentCode int = 204

/*
ClearCartNoContent Cart cleared

swagger:response clearCartNoContent
*/
type ClearCartNoContent struct {
}

// NewClearCartNoContent creates ClearCartNoContent with default headers values
func NewClearCartNoContent() *ClearCartNoContent {

	return &ClearCartNoContent{}
}

// WriteResponse to the client
func (o *ClearCartNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
