// Code generated by go-swagger; DO NOT EDIT.

package cart

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"Adornme/models"
)

// UpdateCartItemHandlerFunc turns a function with the right signature into a update cart item handler
type UpdateCartItemHandlerFunc func(UpdateCartItemParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateCartItemHandlerFunc) Handle(params UpdateCartItemParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateCartItemHandler interface for that can handle valid update cart item params
type UpdateCartItemHandler interface {
	Handle(UpdateCartItemParams, *models.Principal) middleware.Responder
}

// NewUpdateCartItem creates a new http.Handler for the update cart item operation
func NewUpdateCartItem(ctx *middleware.Context, handler UpdateCartItemHandler) *UpdateCartItem {
	return &UpdateCartItem{Context: ctx, Handler: handler}
}

/*
	UpdateCartItem swagger:route PUT /cart Cart updateCartItem

Update item quantity in cart
*/
type UpdateCartItem struct {
	Context *middleware.Context
	Handler UpdateCartItemHandler
}

func (o *UpdateCartItem) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateCartItemParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
