// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Order API
//
//	API specification for shopping cart, checkout, and order management (customer-facing).
//
//	Schemes:
//	  https
//	Host: api.adornme.com
//	BasePath: /v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
