// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API specification for shopping cart, checkout, and order management (customer-facing).\n",
    "title": "Order API",
    "version": "1.0.0"
  },
  "host": "api.adornme.com",
  "basePath": "/v1",
  "paths": {
    "/cart": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Get current user's cart",
        "responses": {
          "200": {
            "description": "Current shopping cart",
            "schema": {
              "$ref": "#/definitions/Cart"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Update item quantity in cart",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CartItemUpdateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Cart updated",
            "schema": {
              "$ref": "#/definitions/Cart"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Add item to cart",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CartItemRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Item added to cart",
            "schema": {
              "$ref": "#/definitions/Cart"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Clear cart",
        "responses": {
          "204": {
            "description": "Cart cleared"
          }
        }
      }
    },
    "/orders": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Orders"
        ],
        "summary": "List user's orders",
        "parameters": [
          {
            "type": "integer",
            "default": 1,
            "name": "page",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 10,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of orders",
            "schema": {
              "$ref": "#/definitions/OrderListResponse"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Orders"
        ],
        "summary": "Place an order from cart",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/OrderCreateRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Order placed successfully",
            "schema": {
              "$ref": "#/definitions/Order"
            }
          },
          "400": {
            "description": "Invalid order request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/orders/{id}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Orders"
        ],
        "summary": "Get order details",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Order details",
            "schema": {
              "$ref": "#/definitions/Order"
            }
          },
          "404": {
            "description": "Order not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Cart": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CartItem"
          }
        },
        "totalPrice": {
          "type": "number",
          "format": "float",
          "example": 2999.5
        }
      }
    },
    "CartItem": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "Gold Ring"
        },
        "price": {
          "type": "number",
          "format": "float",
          "example": 1499.75
        },
        "productId": {
          "type": "integer",
          "example": 101
        },
        "quantity": {
          "type": "integer",
          "example": 2
        },
        "subtotal": {
          "type": "number",
          "format": "float",
          "example": 2999.5
        }
      }
    },
    "CartItemRequest": {
      "type": "object",
      "required": [
        "productId",
        "quantity"
      ],
      "properties": {
        "productId": {
          "type": "integer"
        },
        "quantity": {
          "type": "integer",
          "minimum": 1
        }
      }
    },
    "CartItemUpdateRequest": {
      "type": "object",
      "required": [
        "productId",
        "quantity"
      ],
      "properties": {
        "productId": {
          "type": "integer"
        },
        "quantity": {
          "type": "integer",
          "minimum": 1
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "required": [
        "error",
        "message"
      ],
      "properties": {
        "error": {
          "type": "string",
          "example": "BadRequest"
        },
        "message": {
          "type": "string",
          "example": "Invalid order data"
        }
      }
    },
    "Order": {
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "integer",
          "example": 5001
        },
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CartItem"
          }
        },
        "status": {
          "type": "string",
          "enum": [
            "pending",
            "paid",
            "shipped",
            "delivered",
            "cancelled"
          ],
          "example": "pending"
        },
        "totalPrice": {
          "type": "number",
          "format": "float",
          "example": 2999.5
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        },
        "userId": {
          "type": "integer",
          "example": 101
        }
      }
    },
    "OrderCreateRequest": {
      "type": "object",
      "required": [
        "shippingAddressId",
        "paymentMethod"
      ],
      "properties": {
        "paymentMethod": {
          "type": "string",
          "enum": [
            "cod",
            "card",
            "netbanking",
            "upi"
          ],
          "example": "upi"
        },
        "shippingAddressId": {
          "type": "integer",
          "example": 2001
        }
      }
    },
    "OrderListResponse": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Order"
          }
        },
        "limit": {
          "type": "integer"
        },
        "page": {
          "type": "integer"
        },
        "total": {
          "type": "integer"
        }
      }
    }
  },
  "securityDefinitions": {
    "bearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Manage shopping cart",
      "name": "Cart"
    },
    {
      "description": "Checkout and order management",
      "name": "Orders"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API specification for shopping cart, checkout, and order management (customer-facing).\n",
    "title": "Order API",
    "version": "1.0.0"
  },
  "host": "api.adornme.com",
  "basePath": "/v1",
  "paths": {
    "/cart": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Get current user's cart",
        "responses": {
          "200": {
            "description": "Current shopping cart",
            "schema": {
              "$ref": "#/definitions/Cart"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Update item quantity in cart",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CartItemUpdateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Cart updated",
            "schema": {
              "$ref": "#/definitions/Cart"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Add item to cart",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CartItemRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Item added to cart",
            "schema": {
              "$ref": "#/definitions/Cart"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Clear cart",
        "responses": {
          "204": {
            "description": "Cart cleared"
          }
        }
      }
    },
    "/orders": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Orders"
        ],
        "summary": "List user's orders",
        "parameters": [
          {
            "type": "integer",
            "default": 1,
            "name": "page",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 10,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of orders",
            "schema": {
              "$ref": "#/definitions/OrderListResponse"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Orders"
        ],
        "summary": "Place an order from cart",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/OrderCreateRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Order placed successfully",
            "schema": {
              "$ref": "#/definitions/Order"
            }
          },
          "400": {
            "description": "Invalid order request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/orders/{id}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Orders"
        ],
        "summary": "Get order details",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Order details",
            "schema": {
              "$ref": "#/definitions/Order"
            }
          },
          "404": {
            "description": "Order not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Cart": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CartItem"
          }
        },
        "totalPrice": {
          "type": "number",
          "format": "float",
          "example": 2999.5
        }
      }
    },
    "CartItem": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "Gold Ring"
        },
        "price": {
          "type": "number",
          "format": "float",
          "example": 1499.75
        },
        "productId": {
          "type": "integer",
          "example": 101
        },
        "quantity": {
          "type": "integer",
          "example": 2
        },
        "subtotal": {
          "type": "number",
          "format": "float",
          "example": 2999.5
        }
      }
    },
    "CartItemRequest": {
      "type": "object",
      "required": [
        "productId",
        "quantity"
      ],
      "properties": {
        "productId": {
          "type": "integer"
        },
        "quantity": {
          "type": "integer",
          "minimum": 1
        }
      }
    },
    "CartItemUpdateRequest": {
      "type": "object",
      "required": [
        "productId",
        "quantity"
      ],
      "properties": {
        "productId": {
          "type": "integer"
        },
        "quantity": {
          "type": "integer",
          "minimum": 1
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "required": [
        "error",
        "message"
      ],
      "properties": {
        "error": {
          "type": "string",
          "example": "BadRequest"
        },
        "message": {
          "type": "string",
          "example": "Invalid order data"
        }
      }
    },
    "Order": {
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "integer",
          "example": 5001
        },
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CartItem"
          }
        },
        "status": {
          "type": "string",
          "enum": [
            "pending",
            "paid",
            "shipped",
            "delivered",
            "cancelled"
          ],
          "example": "pending"
        },
        "totalPrice": {
          "type": "number",
          "format": "float",
          "example": 2999.5
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        },
        "userId": {
          "type": "integer",
          "example": 101
        }
      }
    },
    "OrderCreateRequest": {
      "type": "object",
      "required": [
        "shippingAddressId",
        "paymentMethod"
      ],
      "properties": {
        "paymentMethod": {
          "type": "string",
          "enum": [
            "cod",
            "card",
            "netbanking",
            "upi"
          ],
          "example": "upi"
        },
        "shippingAddressId": {
          "type": "integer",
          "example": 2001
        }
      }
    },
    "OrderListResponse": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Order"
          }
        },
        "limit": {
          "type": "integer"
        },
        "page": {
          "type": "integer"
        },
        "total": {
          "type": "integer"
        }
      }
    }
  },
  "securityDefinitions": {
    "bearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Manage shopping cart",
      "name": "Cart"
    },
    {
      "description": "Checkout and order management",
      "name": "Orders"
    }
  ]
}`))
}
