// Code generated by go-swagger; DO NOT EDIT.

package admin_users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteUsersIDNoContentCode is the HTTP code returned for type DeleteUsersIDNoContent
const DeleteUsersIDNoContentCode int = 204

/*
DeleteUsersIDNoContent User deleted

swagger:response deleteUsersIdNoContent
*/
type DeleteUsersIDNoContent struct {
}

// NewDeleteUsersIDNoContent creates DeleteUsersIDNoContent with default headers values
func NewDeleteUsersIDNoContent() *DeleteUsersIDNoContent {

	return &DeleteUsersIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteUsersIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
