// Code generated by go-swagger; DO NOT EDIT.

package admin_users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutUsersIDOKCode is the HTTP code returned for type PutUsersIDOK
const PutUsersIDOKCode int = 200

/*
PutUsersIDOK User updated

swagger:response putUsersIdOK
*/
type PutUsersIDOK struct {
}

// NewPutUsersIDOK creates PutUsersIDOK with default headers values
func NewPutUsersIDOK() *PutUsersIDOK {

	return &PutUsersIDOK{}
}

// WriteResponse to the client
func (o *PutUsersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
