// Code generated by go-swagger; DO NOT EDIT.

package admin_products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"Adornme/models"
)

// CreateProductHandlerFunc turns a function with the right signature into a create product handler
type CreateProductHandlerFunc func(CreateProductParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateProductHandlerFunc) Handle(params CreateProductParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// CreateProductHandler interface for that can handle valid create product params
type CreateProductHandler interface {
	Handle(CreateProductParams, *models.Principal) middleware.Responder
}

// NewCreateProduct creates a new http.Handler for the create product operation
func NewCreateProduct(ctx *middleware.Context, handler CreateProductHandler) *CreateProduct {
	return &CreateProduct{Context: ctx, Handler: handler}
}

/*
	CreateProduct swagger:route POST /products AdminProducts createProduct

Create a new product
*/
type CreateProduct struct {
	Context *middleware.Context
	Handler CreateProductHandler
}

func (o *CreateProduct) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateProductParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
