// Code generated by go-swagger; DO NOT EDIT.

package admin_products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateProductCreatedCode is the HTTP code returned for type CreateProductCreated
const CreateProductCreatedCode int = 201

/*
CreateProductCreated Product created successfully

swagger:response createProductCreated
*/
type CreateProductCreated struct {
}

// NewCreateProductCreated creates CreateProductCreated with default headers values
func NewCreateProductCreated() *CreateProductCreated {

	return &CreateProductCreated{}
}

// WriteResponse to the client
func (o *CreateProductCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// CreateProductBadRequestCode is the HTTP code returned for type CreateProductBadRequest
const CreateProductBadRequestCode int = 400

/*
CreateProductBadRequest Validation error

swagger:response createProductBadRequest
*/
type CreateProductBadRequest struct {
}

// NewCreateProductBadRequest creates CreateProductBadRequest with default headers values
func NewCreateProductBadRequest() *CreateProductBadRequest {

	return &CreateProductBadRequest{}
}

// WriteResponse to the client
func (o *CreateProductBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateProductUnauthorizedCode is the HTTP code returned for type CreateProductUnauthorized
const CreateProductUnauthorizedCode int = 401

/*
CreateProductUnauthorized Unauthorized

swagger:response createProductUnauthorized
*/
type CreateProductUnauthorized struct {
}

// NewCreateProductUnauthorized creates CreateProductUnauthorized with default headers values
func NewCreateProductUnauthorized() *CreateProductUnauthorized {

	return &CreateProductUnauthorized{}
}

// WriteResponse to the client
func (o *CreateProductUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
