// Code generated by go-swagger; DO NOT EDIT.

package admin_products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteProductNoContentCode is the HTTP code returned for type DeleteProductNoContent
const DeleteProductNoContentCode int = 204

/*
DeleteProductNoContent Product deleted

swagger:response deleteProductNoContent
*/
type DeleteProductNoContent struct {
}

// NewDeleteProductNoContent creates DeleteProductNoContent with default headers values
func NewDeleteProductNoContent() *DeleteProductNoContent {

	return &DeleteProductNoContent{}
}

// WriteResponse to the client
func (o *DeleteProductNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
