// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// PlaceOrderCreatedCode is the HTTP code returned for type PlaceOrderCreated
const PlaceOrderCreatedCode int = 201

/*
PlaceOrderCreated Order placed successfully

swagger:response placeOrderCreated
*/
type PlaceOrderCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Order `json:"body,omitempty"`
}

// NewPlaceOrderCreated creates PlaceOrderCreated with default headers values
func NewPlaceOrderCreated() *PlaceOrderCreated {

	return &PlaceOrderCreated{}
}

// WithPayload adds the payload to the place order created response
func (o *PlaceOrderCreated) WithPayload(payload *models.Order) *PlaceOrderCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the place order created response
func (o *PlaceOrderCreated) SetPayload(payload *models.Order) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PlaceOrderCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PlaceOrderBadRequestCode is the HTTP code returned for type PlaceOrderBadRequest
const PlaceOrderBadRequestCode int = 400

/*
PlaceOrderBadRequest Invalid order request

swagger:response placeOrderBadRequest
*/
type PlaceOrderBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPlaceOrderBadRequest creates PlaceOrderBadRequest with default headers values
func NewPlaceOrderBadRequest() *PlaceOrderBadRequest {

	return &PlaceOrderBadRequest{}
}

// WithPayload adds the payload to the place order bad request response
func (o *PlaceOrderBadRequest) WithPayload(payload *models.ErrorResponse) *PlaceOrderBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the place order bad request response
func (o *PlaceOrderBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PlaceOrderBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
