// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProductUpdateRequest product update request
//
// swagger:model ProductUpdateRequest
type ProductUpdateRequest struct {

	// category Id
	CategoryID int64 `json:"categoryId,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// images
	Images []strfmt.URI `json:"images"`

	// name
	Name string `json:"name,omitempty"`

	// price
	Price float32 `json:"price,omitempty"`

	// stock
	Stock int64 `json:"stock,omitempty"`
}

// Validate validates this product update request
func (m *ProductUpdateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateImages(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProductUpdateRequest) validateImages(formats strfmt.Registry) error {
	if swag.IsZero(m.Images) { // not required
		return nil
	}

	for i := 0; i < len(m.Images); i++ {

		if err := validate.FormatOf("images"+"."+strconv.Itoa(i), "body", "uri", m.Images[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this product update request based on context it is used
func (m *ProductUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProductUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductUpdateRequest) UnmarshalBinary(b []byte) error {
	var res ProductUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
