// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/AdornmeCode/Products/models"
)

// GetProductsIDOKCode is the HTTP code returned for type GetProductsIDOK
const GetProductsIDOKCode int = 200

/*
GetProductsIDOK Product details

swagger:response getProductsIdOK
*/
type GetProductsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Product `json:"body,omitempty"`
}

// NewGetProductsIDOK creates GetProductsIDOK with default headers values
func NewGetProductsIDOK() *GetProductsIDOK {

	return &GetProductsIDOK{}
}

// WithPayload adds the payload to the get products Id o k response
func (o *GetProductsIDOK) WithPayload(payload *models.Product) *GetProductsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get products Id o k response
func (o *GetProductsIDOK) SetPayload(payload *models.Product) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProductsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetProductsIDNotFoundCode is the HTTP code returned for type GetProductsIDNotFound
const GetProductsIDNotFoundCode int = 404

/*
GetProductsIDNotFound Product not found

swagger:response getProductsIdNotFound
*/
type GetProductsIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetProductsIDNotFound creates GetProductsIDNotFound with default headers values
func NewGetProductsIDNotFound() *GetProductsIDNotFound {

	return &GetProductsIDNotFound{}
}

// WithPayload adds the payload to the get products Id not found response
func (o *GetProductsIDNotFound) WithPayload(payload *models.ErrorResponse) *GetProductsIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get products Id not found response
func (o *GetProductsIDNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProductsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
