// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/AdornmeCode/Products/models"
)

// PostProductsCreatedCode is the HTTP code returned for type PostProductsCreated
const PostProductsCreatedCode int = 201

/*
PostProductsCreated Product created successfully

swagger:response postProductsCreated
*/
type PostProductsCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Product `json:"body,omitempty"`
}

// NewPostProductsCreated creates PostProductsCreated with default headers values
func NewPostProductsCreated() *PostProductsCreated {

	return &PostProductsCreated{}
}

// WithPayload adds the payload to the post products created response
func (o *PostProductsCreated) WithPayload(payload *models.Product) *PostProductsCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post products created response
func (o *PostProductsCreated) SetPayload(payload *models.Product) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostProductsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostProductsBadRequestCode is the HTTP code returned for type PostProductsBadRequest
const PostProductsBadRequestCode int = 400

/*
PostProductsBadRequest Validation error

swagger:response postProductsBadRequest
*/
type PostProductsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostProductsBadRequest creates PostProductsBadRequest with default headers values
func NewPostProductsBadRequest() *PostProductsBadRequest {

	return &PostProductsBadRequest{}
}

// WithPayload adds the payload to the post products bad request response
func (o *PostProductsBadRequest) WithPayload(payload *models.ErrorResponse) *PostProductsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post products bad request response
func (o *PostProductsBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostProductsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostProductsUnauthorizedCode is the HTTP code returned for type PostProductsUnauthorized
const PostProductsUnauthorizedCode int = 401

/*
PostProductsUnauthorized Unauthorized

swagger:response postProductsUnauthorized
*/
type PostProductsUnauthorized struct {
}

// NewPostProductsUnauthorized creates PostProductsUnauthorized with default headers values
func NewPostProductsUnauthorized() *PostProductsUnauthorized {

	return &PostProductsUnauthorized{}
}

// WriteResponse to the client
func (o *PostProductsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
