// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostProductsHandlerFunc turns a function with the right signature into a post products handler
type PostProductsHandlerFunc func(PostProductsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostProductsHandlerFunc) Handle(params PostProductsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostProductsHandler interface for that can handle valid post products params
type PostProductsHandler interface {
	Handle(PostProductsParams, interface{}) middleware.Responder
}

// NewPostProducts creates a new http.Handler for the post products operation
func NewPostProducts(ctx *middleware.Context, handler PostProductsHandler) *PostProducts {
	return &PostProducts{Context: ctx, Handler: handler}
}

/*
	PostProducts swagger:route POST /products Products postProducts

Create a new product (Admin only)
*/
type PostProducts struct {
	Context *middleware.Context
	Handler PostProductsHandler
}

func (o *PostProducts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostProductsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
