// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/AdornmeCode/Products/models"
)

// PutProductsIDOKCode is the HTTP code returned for type PutProductsIDOK
const PutProductsIDOKCode int = 200

/*
PutProductsIDOK Product updated successfully

swagger:response putProductsIdOK
*/
type PutProductsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Product `json:"body,omitempty"`
}

// NewPutProductsIDOK creates PutProductsIDOK with default headers values
func NewPutProductsIDOK() *PutProductsIDOK {

	return &PutProductsIDOK{}
}

// WithPayload adds the payload to the put products Id o k response
func (o *PutProductsIDOK) WithPayload(payload *models.Product) *PutProductsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put products Id o k response
func (o *PutProductsIDOK) SetPayload(payload *models.Product) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutProductsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutProductsIDBadRequestCode is the HTTP code returned for type PutProductsIDBadRequest
const PutProductsIDBadRequestCode int = 400

/*
PutProductsIDBadRequest Validation error

swagger:response putProductsIdBadRequest
*/
type PutProductsIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPutProductsIDBadRequest creates PutProductsIDBadRequest with default headers values
func NewPutProductsIDBadRequest() *PutProductsIDBadRequest {

	return &PutProductsIDBadRequest{}
}

// WithPayload adds the payload to the put products Id bad request response
func (o *PutProductsIDBadRequest) WithPayload(payload *models.ErrorResponse) *PutProductsIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put products Id bad request response
func (o *PutProductsIDBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutProductsIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutProductsIDNotFoundCode is the HTTP code returned for type PutProductsIDNotFound
const PutProductsIDNotFoundCode int = 404

/*
PutProductsIDNotFound Product not found

swagger:response putProductsIdNotFound
*/
type PutProductsIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPutProductsIDNotFound creates PutProductsIDNotFound with default headers values
func NewPutProductsIDNotFound() *PutProductsIDNotFound {

	return &PutProductsIDNotFound{}
}

// WithPayload adds the payload to the put products Id not found response
func (o *PutProductsIDNotFound) WithPayload(payload *models.ErrorResponse) *PutProductsIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put products Id not found response
func (o *PutProductsIDNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutProductsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
