// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Product API
//
//	API specification for managing products in the e-commerce system. This API is used by the customer-facing side of the application.
//
//	Schemes:
//	  https
//	Host: api.adornme.com
//	BasePath: /v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
