// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API specification for managing products in the e-commerce system. This API is used by the customer-facing side of the application.\n",
    "title": "Product API",
    "version": "1.0.0"
  },
  "host": "api.adornme.com",
  "basePath": "/v1",
  "paths": {
    "/products": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "List products",
        "parameters": [
          {
            "type": "integer",
            "default": 1,
            "description": "Page number",
            "name": "page",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 20,
            "description": "Number of items per page",
            "name": "limit",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Search term to filter products",
            "name": "search",
            "in": "query"
          },
          {
            "type": "integer",
            "description": "Filter products by category ID",
            "name": "categoryId",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A paginated list of products",
            "schema": {
              "$ref": "#/definitions/ProductListResponse"
            }
          },
          "400": {
            "description": "Invalid query parameters",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Products"
        ],
        "summary": "Create a new product (Admin only)",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProductCreateRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Product created successfully",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "400": {
            "description": "Validation error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Get product by ID",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Product details",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "404": {
            "description": "Product not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Products"
        ],
        "summary": "Update a product (Admin only)",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProductUpdateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Product updated successfully",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "400": {
            "description": "Validation error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "404": {
            "description": "Product not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Products"
        ],
        "summary": "Delete a product (Admin only)",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Product deleted successfully"
          },
          "404": {
            "description": "Product not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "type": "object",
      "required": [
        "error",
        "message"
      ],
      "properties": {
        "error": {
          "type": "string",
          "example": "BadRequest"
        },
        "message": {
          "type": "string",
          "example": "Invalid request parameters"
        }
      }
    },
    "Product": {
      "type": "object",
      "required": [
        "id",
        "name",
        "price",
        "stock",
        "categoryId"
      ],
      "properties": {
        "categoryId": {
          "type": "integer",
          "example": 5
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string",
          "example": "22K pure gold necklace with intricate design"
        },
        "id": {
          "type": "integer",
          "example": 101
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "https://cdn.adornme.com/products/101-1.jpg",
            "https://cdn.adornme.com/products/101-2.jpg"
          ]
        },
        "name": {
          "type": "string",
          "example": "Gold Necklace"
        },
        "price": {
          "type": "number",
          "format": "float",
          "example": 14999.99
        },
        "stock": {
          "type": "integer",
          "example": 20
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "ProductCreateRequest": {
      "type": "object",
      "required": [
        "name",
        "price",
        "stock",
        "categoryId"
      ],
      "properties": {
        "categoryId": {
          "type": "integer"
        },
        "description": {
          "type": "string"
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "type": "string"
        },
        "price": {
          "type": "number",
          "format": "float"
        },
        "stock": {
          "type": "integer"
        }
      }
    },
    "ProductListResponse": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Product"
          }
        },
        "limit": {
          "type": "integer",
          "example": 20
        },
        "page": {
          "type": "integer",
          "example": 1
        },
        "total": {
          "type": "integer",
          "example": 100
        }
      }
    },
    "ProductUpdateRequest": {
      "type": "object",
      "properties": {
        "categoryId": {
          "type": "integer"
        },
        "description": {
          "type": "string"
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "type": "string"
        },
        "price": {
          "type": "number",
          "format": "float"
        },
        "stock": {
          "type": "integer"
        }
      }
    }
  },
  "securityDefinitions": {
    "bearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Operations related to products",
      "name": "Products"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API specification for managing products in the e-commerce system. This API is used by the customer-facing side of the application.\n",
    "title": "Product API",
    "version": "1.0.0"
  },
  "host": "api.adornme.com",
  "basePath": "/v1",
  "paths": {
    "/products": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "List products",
        "parameters": [
          {
            "type": "integer",
            "default": 1,
            "description": "Page number",
            "name": "page",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 20,
            "description": "Number of items per page",
            "name": "limit",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Search term to filter products",
            "name": "search",
            "in": "query"
          },
          {
            "type": "integer",
            "description": "Filter products by category ID",
            "name": "categoryId",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A paginated list of products",
            "schema": {
              "$ref": "#/definitions/ProductListResponse"
            }
          },
          "400": {
            "description": "Invalid query parameters",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Products"
        ],
        "summary": "Create a new product (Admin only)",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProductCreateRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Product created successfully",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "400": {
            "description": "Validation error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Get product by ID",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Product details",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "404": {
            "description": "Product not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Products"
        ],
        "summary": "Update a product (Admin only)",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProductUpdateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Product updated successfully",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "400": {
            "description": "Validation error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "404": {
            "description": "Product not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Products"
        ],
        "summary": "Delete a product (Admin only)",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Product deleted successfully"
          },
          "404": {
            "description": "Product not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorResponse": {
      "type": "object",
      "required": [
        "error",
        "message"
      ],
      "properties": {
        "error": {
          "type": "string",
          "example": "BadRequest"
        },
        "message": {
          "type": "string",
          "example": "Invalid request parameters"
        }
      }
    },
    "Product": {
      "type": "object",
      "required": [
        "id",
        "name",
        "price",
        "stock",
        "categoryId"
      ],
      "properties": {
        "categoryId": {
          "type": "integer",
          "example": 5
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string",
          "example": "22K pure gold necklace with intricate design"
        },
        "id": {
          "type": "integer",
          "example": 101
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "https://cdn.adornme.com/products/101-1.jpg",
            "https://cdn.adornme.com/products/101-2.jpg"
          ]
        },
        "name": {
          "type": "string",
          "example": "Gold Necklace"
        },
        "price": {
          "type": "number",
          "format": "float",
          "example": 14999.99
        },
        "stock": {
          "type": "integer",
          "example": 20
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "ProductCreateRequest": {
      "type": "object",
      "required": [
        "name",
        "price",
        "stock",
        "categoryId"
      ],
      "properties": {
        "categoryId": {
          "type": "integer"
        },
        "description": {
          "type": "string"
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "type": "string"
        },
        "price": {
          "type": "number",
          "format": "float"
        },
        "stock": {
          "type": "integer"
        }
      }
    },
    "ProductListResponse": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Product"
          }
        },
        "limit": {
          "type": "integer",
          "example": 20
        },
        "page": {
          "type": "integer",
          "example": 1
        },
        "total": {
          "type": "integer",
          "example": 100
        }
      }
    },
    "ProductUpdateRequest": {
      "type": "object",
      "properties": {
        "categoryId": {
          "type": "integer"
        },
        "description": {
          "type": "string"
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "type": "string"
        },
        "price": {
          "type": "number",
          "format": "float"
        },
        "stock": {
          "type": "integer"
        }
      }
    }
  },
  "securityDefinitions": {
    "bearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "Operations related to products",
      "name": "Products"
    }
  ]
}`))
}
