openapi: 3.0.3
info:
  title: Orders API
  version: 1.0.0
  description: |
    API specification for shopping cart, checkout, and order management (customer-facing).

servers:
  - url: https://api.adornme.com/v1
    description: Production server
  - url: https://staging-api.adornme.com/v1
    description: Staging server

tags:
  - name: Cart
    description: Manage shopping cart
  - name: Orders
    description: Checkout and order management

paths:
  /cart:
    get:
      summary: Get current user's cart
      tags: [Cart]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Current shopping cart
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "401":
          description: Unauthorized

    post:
      summary: Add item to cart
      tags: [Cart]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CartItemRequest"
      responses:
        "200":
          description: Item added to cart
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"

    put:
      summary: Update item quantity in cart
      tags: [Cart]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CartItemUpdateRequest"
      responses:
        "200":
          description: Cart updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"

    delete:
      summary: Clear cart
      tags: [Cart]
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Cart cleared

  /orders:
    post:
      summary: Place an order from cart
      tags: [Orders]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderCreateRequest"
      responses:
        "201":
          description: Order placed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "400":
          description: Invalid order request

    get:
      summary: List user's orders
      tags: [Orders]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: Paginated list of orders
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderListResponse"

  /orders/{id}:
    get:
      summary: Get order details
      tags: [Orders]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: Order details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: Order not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Cart:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/CartItem"
        totalPrice:
          type: number
          format: float
          example: 2999.50

    CartItem:
      type: object
      properties:
        productId:
          type: integer
          example: 101
        name:
          type: string
          example: Gold Ring
        quantity:
          type: integer
          example: 2
        price:
          type: number
          format: float
          example: 1499.75
        subtotal:
          type: number
          format: float
          example: 2999.50

    CartItemRequest:
      type: object
      required: [productId, quantity]
      properties:
        productId:
          type: integer
        quantity:
          type: integer
          minimum: 1

    CartItemUpdateRequest:
      type: object
      required: [productId, quantity]
      properties:
        productId:
          type: integer
        quantity:
          type: integer
          minimum: 1

    Order:
      type: object
      properties:
        id:
          type: integer
          example: 5001
        userId:
          type: integer
          example: 101
        items:
          type: array
          items:
            $ref: "#/components/schemas/CartItem"
        totalPrice:
          type: number
          format: float
          example: 2999.50
        status:
          type: string
          enum: [pending, paid, shipped, delivered, cancelled]
          example: pending
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    OrderCreateRequest:
      type: object
      required: [shippingAddressId, paymentMethod]
      properties:
        shippingAddressId:
          type: integer
          example: 2001
        paymentMethod:
          type: string
          enum: [cod, card, netbanking, upi]
          example: upi

    OrderListResponse:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        items:
          type: array
          items:
            $ref: "#/components/schemas/Order"

    ErrorResponse:
      type: object
      required: [error, message]
      properties:
        error:
          type: string
          example: BadRequest
        message:
          type: string
          example: Invalid order data
