package main

import (
	"log"
	"net/http"

	"Adornme/restapi"
	"Adornme/restapi/operations"

	"github.com/go-openapi/loads"
	httpSwagger "github.com/swaggo/http-swagger"
)

func main() {
	// Load the embedded Swagger spec
	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln("Error loading swagger spec:", err)
	}

	api := operations.NewAdronmeCodeAPI(swaggerSpec)
	server := restapi.NewServer(api)
	defer server.Shutdown()

	server.ConfigureAPI()

	server.Host = "0.0.0.0"
	server.Port = 8080
	server.TLSCertificate = ""
	server.TLSCertificateKey = ""

	// Use a single HTTP mux to handle both API and Swagger UI
	mux := http.NewServeMux()

	// Register API handlers generated by go-swagger
	handler := server.GetHandler() // this is the main API handler
	mux.Handle("/", handler)

	// Register Swagger UI handler
	mux.Handle("/docs/", httpSwagger.WrapHandler)

	// Log accessible URLs
	log.Println("🚀 Server started at http://0.0.0.0:8080")
	log.Println("📘 Swagger UI available at http://<EC2-PUBLIC-IP>:8080/docs/index.html")

	// Start the server
	if err := http.ListenAndServe(":8080", mux); err != nil {
		log.Fatalf("Server failed: %v", err)
	}
}
