// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"Adornme/models"
	"Adornme/restapi/operations/admin_products"
	"Adornme/restapi/operations/admin_users"
	"Adornme/restapi/operations/cart"
	"Adornme/restapi/operations/orders"
	"Adornme/restapi/operations/payments"
	"Adornme/restapi/operations/shipping"
	"Adornme/restapi/operations/users"
)

// NewAdronmeCodeAPI creates a new AdronmeCode instance
func NewAdronmeCodeAPI(spec *loads.Document) *AdronmeCodeAPI {
	return &AdronmeCodeAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		CartAddItemToCartHandler: cart.AddItemToCartHandlerFunc(func(params cart.AddItemToCartParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation cart.AddItemToCart has not yet been implemented")
		}),
		ShippingAddShippingAddressHandler: shipping.AddShippingAddressHandlerFunc(func(params shipping.AddShippingAddressParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation shipping.AddShippingAddress has not yet been implemented")
		}),
		CartClearCartHandler: cart.ClearCartHandlerFunc(func(params cart.ClearCartParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation cart.ClearCart has not yet been implemented")
		}),
		PaymentsConfirmPaymentHandler: payments.ConfirmPaymentHandlerFunc(func(params payments.ConfirmPaymentParams) middleware.Responder {
			return middleware.NotImplemented("operation payments.ConfirmPayment has not yet been implemented")
		}),
		AdminProductsCreateProductHandler: admin_products.CreateProductHandlerFunc(func(params admin_products.CreateProductParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation admin_products.CreateProduct has not yet been implemented")
		}),
		AdminProductsDeleteProductHandler: admin_products.DeleteProductHandlerFunc(func(params admin_products.DeleteProductParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation admin_products.DeleteProduct has not yet been implemented")
		}),
		ShippingDeleteShippingAddressHandler: shipping.DeleteShippingAddressHandlerFunc(func(params shipping.DeleteShippingAddressParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation shipping.DeleteShippingAddress has not yet been implemented")
		}),
		AdminUsersDeleteUserHandler: admin_users.DeleteUserHandlerFunc(func(params admin_users.DeleteUserParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation admin_users.DeleteUser has not yet been implemented")
		}),
		CartGetCartHandler: cart.GetCartHandlerFunc(func(params cart.GetCartParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation cart.GetCart has not yet been implemented")
		}),
		OrdersGetOrderHandler: orders.GetOrderHandlerFunc(func(params orders.GetOrderParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation orders.GetOrder has not yet been implemented")
		}),
		PaymentsGetPaymentHandler: payments.GetPaymentHandlerFunc(func(params payments.GetPaymentParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation payments.GetPayment has not yet been implemented")
		}),
		AdminUsersGetUserHandler: admin_users.GetUserHandlerFunc(func(params admin_users.GetUserParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation admin_users.GetUser has not yet been implemented")
		}),
		UsersGetUserProfileHandler: users.GetUserProfileHandlerFunc(func(params users.GetUserProfileParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation users.GetUserProfile has not yet been implemented")
		}),
		PaymentsInitiatePaymentHandler: payments.InitiatePaymentHandlerFunc(func(params payments.InitiatePaymentParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation payments.InitiatePayment has not yet been implemented")
		}),
		OrdersListOrdersHandler: orders.ListOrdersHandlerFunc(func(params orders.ListOrdersParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation orders.ListOrders has not yet been implemented")
		}),
		ShippingListShippingAddressesHandler: shipping.ListShippingAddressesHandlerFunc(func(params shipping.ListShippingAddressesParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation shipping.ListShippingAddresses has not yet been implemented")
		}),
		ShippingListShippingOptionsHandler: shipping.ListShippingOptionsHandlerFunc(func(params shipping.ListShippingOptionsParams) middleware.Responder {
			return middleware.NotImplemented("operation shipping.ListShippingOptions has not yet been implemented")
		}),
		AdminUsersListUsersHandler: admin_users.ListUsersHandlerFunc(func(params admin_users.ListUsersParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation admin_users.ListUsers has not yet been implemented")
		}),
		UsersLoginUserHandler: users.LoginUserHandlerFunc(func(params users.LoginUserParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation users.LoginUser has not yet been implemented")
		}),
		OrdersPlaceOrderHandler: orders.PlaceOrderHandlerFunc(func(params orders.PlaceOrderParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation orders.PlaceOrder has not yet been implemented")
		}),
		PaymentsRefundPaymentHandler: payments.RefundPaymentHandlerFunc(func(params payments.RefundPaymentParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation payments.RefundPayment has not yet been implemented")
		}),
		UsersRegisterUserHandler: users.RegisterUserHandlerFunc(func(params users.RegisterUserParams) middleware.Responder {
			return middleware.NotImplemented("operation users.RegisterUser has not yet been implemented")
		}),
		UsersRequestPasswordResetHandler: users.RequestPasswordResetHandlerFunc(func(params users.RequestPasswordResetParams) middleware.Responder {
			return middleware.NotImplemented("operation users.RequestPasswordReset has not yet been implemented")
		}),
		UsersResetPasswordHandler: users.ResetPasswordHandlerFunc(func(params users.ResetPasswordParams) middleware.Responder {
			return middleware.NotImplemented("operation users.ResetPassword has not yet been implemented")
		}),
		ShippingTrackShipmentHandler: shipping.TrackShipmentHandlerFunc(func(params shipping.TrackShipmentParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation shipping.TrackShipment has not yet been implemented")
		}),
		CartUpdateCartItemHandler: cart.UpdateCartItemHandlerFunc(func(params cart.UpdateCartItemParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation cart.UpdateCartItem has not yet been implemented")
		}),
		AdminProductsUpdateProductHandler: admin_products.UpdateProductHandlerFunc(func(params admin_products.UpdateProductParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation admin_products.UpdateProduct has not yet been implemented")
		}),
		ShippingUpdateShippingAddressHandler: shipping.UpdateShippingAddressHandlerFunc(func(params shipping.UpdateShippingAddressParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation shipping.UpdateShippingAddress has not yet been implemented")
		}),
		AdminUsersUpdateUserHandler: admin_users.UpdateUserHandlerFunc(func(params admin_users.UpdateUserParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation admin_users.UpdateUser has not yet been implemented")
		}),
		UsersUpdateUserProfileHandler: users.UpdateUserProfileHandlerFunc(func(params users.UpdateUserProfileParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation users.UpdateUserProfile has not yet been implemented")
		}),

		// Applies when the "Authorization" header is set
		BearerAuthAuth: func(token string) (*models.Principal, error) {
			return nil, errors.NotImplemented("api key auth (bearerAuth) Authorization from header param [Authorization] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*AdronmeCodeAPI the adronme code API */
type AdronmeCodeAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// BearerAuthAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Authorization provided in the header
	BearerAuthAuth func(string) (*models.Principal, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// CartAddItemToCartHandler sets the operation handler for the add item to cart operation
	CartAddItemToCartHandler cart.AddItemToCartHandler
	// ShippingAddShippingAddressHandler sets the operation handler for the add shipping address operation
	ShippingAddShippingAddressHandler shipping.AddShippingAddressHandler
	// CartClearCartHandler sets the operation handler for the clear cart operation
	CartClearCartHandler cart.ClearCartHandler
	// PaymentsConfirmPaymentHandler sets the operation handler for the confirm payment operation
	PaymentsConfirmPaymentHandler payments.ConfirmPaymentHandler
	// AdminProductsCreateProductHandler sets the operation handler for the create product operation
	AdminProductsCreateProductHandler admin_products.CreateProductHandler
	// AdminProductsDeleteProductHandler sets the operation handler for the delete product operation
	AdminProductsDeleteProductHandler admin_products.DeleteProductHandler
	// ShippingDeleteShippingAddressHandler sets the operation handler for the delete shipping address operation
	ShippingDeleteShippingAddressHandler shipping.DeleteShippingAddressHandler
	// AdminUsersDeleteUserHandler sets the operation handler for the delete user operation
	AdminUsersDeleteUserHandler admin_users.DeleteUserHandler
	// CartGetCartHandler sets the operation handler for the get cart operation
	CartGetCartHandler cart.GetCartHandler
	// OrdersGetOrderHandler sets the operation handler for the get order operation
	OrdersGetOrderHandler orders.GetOrderHandler
	// PaymentsGetPaymentHandler sets the operation handler for the get payment operation
	PaymentsGetPaymentHandler payments.GetPaymentHandler
	// AdminUsersGetUserHandler sets the operation handler for the get user operation
	AdminUsersGetUserHandler admin_users.GetUserHandler
	// UsersGetUserProfileHandler sets the operation handler for the get user profile operation
	UsersGetUserProfileHandler users.GetUserProfileHandler
	// PaymentsInitiatePaymentHandler sets the operation handler for the initiate payment operation
	PaymentsInitiatePaymentHandler payments.InitiatePaymentHandler
	// OrdersListOrdersHandler sets the operation handler for the list orders operation
	OrdersListOrdersHandler orders.ListOrdersHandler
	// ShippingListShippingAddressesHandler sets the operation handler for the list shipping addresses operation
	ShippingListShippingAddressesHandler shipping.ListShippingAddressesHandler
	// ShippingListShippingOptionsHandler sets the operation handler for the list shipping options operation
	ShippingListShippingOptionsHandler shipping.ListShippingOptionsHandler
	// AdminUsersListUsersHandler sets the operation handler for the list users operation
	AdminUsersListUsersHandler admin_users.ListUsersHandler
	// UsersLoginUserHandler sets the operation handler for the login user operation
	UsersLoginUserHandler users.LoginUserHandler
	// OrdersPlaceOrderHandler sets the operation handler for the place order operation
	OrdersPlaceOrderHandler orders.PlaceOrderHandler
	// PaymentsRefundPaymentHandler sets the operation handler for the refund payment operation
	PaymentsRefundPaymentHandler payments.RefundPaymentHandler
	// UsersRegisterUserHandler sets the operation handler for the register user operation
	UsersRegisterUserHandler users.RegisterUserHandler
	// UsersRequestPasswordResetHandler sets the operation handler for the request password reset operation
	UsersRequestPasswordResetHandler users.RequestPasswordResetHandler
	// UsersResetPasswordHandler sets the operation handler for the reset password operation
	UsersResetPasswordHandler users.ResetPasswordHandler
	// ShippingTrackShipmentHandler sets the operation handler for the track shipment operation
	ShippingTrackShipmentHandler shipping.TrackShipmentHandler
	// CartUpdateCartItemHandler sets the operation handler for the update cart item operation
	CartUpdateCartItemHandler cart.UpdateCartItemHandler
	// AdminProductsUpdateProductHandler sets the operation handler for the update product operation
	AdminProductsUpdateProductHandler admin_products.UpdateProductHandler
	// ShippingUpdateShippingAddressHandler sets the operation handler for the update shipping address operation
	ShippingUpdateShippingAddressHandler shipping.UpdateShippingAddressHandler
	// AdminUsersUpdateUserHandler sets the operation handler for the update user operation
	AdminUsersUpdateUserHandler admin_users.UpdateUserHandler
	// UsersUpdateUserProfileHandler sets the operation handler for the update user profile operation
	UsersUpdateUserProfileHandler users.UpdateUserProfileHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *AdronmeCodeAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *AdronmeCodeAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *AdronmeCodeAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *AdronmeCodeAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *AdronmeCodeAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *AdronmeCodeAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *AdronmeCodeAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *AdronmeCodeAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *AdronmeCodeAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the AdronmeCodeAPI
func (o *AdronmeCodeAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BearerAuthAuth == nil {
		unregistered = append(unregistered, "AuthorizationAuth")
	}

	if o.CartAddItemToCartHandler == nil {
		unregistered = append(unregistered, "cart.AddItemToCartHandler")
	}
	if o.ShippingAddShippingAddressHandler == nil {
		unregistered = append(unregistered, "shipping.AddShippingAddressHandler")
	}
	if o.CartClearCartHandler == nil {
		unregistered = append(unregistered, "cart.ClearCartHandler")
	}
	if o.PaymentsConfirmPaymentHandler == nil {
		unregistered = append(unregistered, "payments.ConfirmPaymentHandler")
	}
	if o.AdminProductsCreateProductHandler == nil {
		unregistered = append(unregistered, "admin_products.CreateProductHandler")
	}
	if o.AdminProductsDeleteProductHandler == nil {
		unregistered = append(unregistered, "admin_products.DeleteProductHandler")
	}
	if o.ShippingDeleteShippingAddressHandler == nil {
		unregistered = append(unregistered, "shipping.DeleteShippingAddressHandler")
	}
	if o.AdminUsersDeleteUserHandler == nil {
		unregistered = append(unregistered, "admin_users.DeleteUserHandler")
	}
	if o.CartGetCartHandler == nil {
		unregistered = append(unregistered, "cart.GetCartHandler")
	}
	if o.OrdersGetOrderHandler == nil {
		unregistered = append(unregistered, "orders.GetOrderHandler")
	}
	if o.PaymentsGetPaymentHandler == nil {
		unregistered = append(unregistered, "payments.GetPaymentHandler")
	}
	if o.AdminUsersGetUserHandler == nil {
		unregistered = append(unregistered, "admin_users.GetUserHandler")
	}
	if o.UsersGetUserProfileHandler == nil {
		unregistered = append(unregistered, "users.GetUserProfileHandler")
	}
	if o.PaymentsInitiatePaymentHandler == nil {
		unregistered = append(unregistered, "payments.InitiatePaymentHandler")
	}
	if o.OrdersListOrdersHandler == nil {
		unregistered = append(unregistered, "orders.ListOrdersHandler")
	}
	if o.ShippingListShippingAddressesHandler == nil {
		unregistered = append(unregistered, "shipping.ListShippingAddressesHandler")
	}
	if o.ShippingListShippingOptionsHandler == nil {
		unregistered = append(unregistered, "shipping.ListShippingOptionsHandler")
	}
	if o.AdminUsersListUsersHandler == nil {
		unregistered = append(unregistered, "admin_users.ListUsersHandler")
	}
	if o.UsersLoginUserHandler == nil {
		unregistered = append(unregistered, "users.LoginUserHandler")
	}
	if o.OrdersPlaceOrderHandler == nil {
		unregistered = append(unregistered, "orders.PlaceOrderHandler")
	}
	if o.PaymentsRefundPaymentHandler == nil {
		unregistered = append(unregistered, "payments.RefundPaymentHandler")
	}
	if o.UsersRegisterUserHandler == nil {
		unregistered = append(unregistered, "users.RegisterUserHandler")
	}
	if o.UsersRequestPasswordResetHandler == nil {
		unregistered = append(unregistered, "users.RequestPasswordResetHandler")
	}
	if o.UsersResetPasswordHandler == nil {
		unregistered = append(unregistered, "users.ResetPasswordHandler")
	}
	if o.ShippingTrackShipmentHandler == nil {
		unregistered = append(unregistered, "shipping.TrackShipmentHandler")
	}
	if o.CartUpdateCartItemHandler == nil {
		unregistered = append(unregistered, "cart.UpdateCartItemHandler")
	}
	if o.AdminProductsUpdateProductHandler == nil {
		unregistered = append(unregistered, "admin_products.UpdateProductHandler")
	}
	if o.ShippingUpdateShippingAddressHandler == nil {
		unregistered = append(unregistered, "shipping.UpdateShippingAddressHandler")
	}
	if o.AdminUsersUpdateUserHandler == nil {
		unregistered = append(unregistered, "admin_users.UpdateUserHandler")
	}
	if o.UsersUpdateUserProfileHandler == nil {
		unregistered = append(unregistered, "users.UpdateUserProfileHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *AdronmeCodeAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *AdronmeCodeAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "bearerAuth":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, func(token string) (interface{}, error) {
				return o.BearerAuthAuth(token)
			})

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *AdronmeCodeAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *AdronmeCodeAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *AdronmeCodeAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *AdronmeCodeAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the adronme code API
func (o *AdronmeCodeAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *AdronmeCodeAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/cart"] = cart.NewAddItemToCart(o.context, o.CartAddItemToCartHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/shipping/addresses"] = shipping.NewAddShippingAddress(o.context, o.ShippingAddShippingAddressHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/cart"] = cart.NewClearCart(o.context, o.CartClearCartHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/payments/{id}/confirm"] = payments.NewConfirmPayment(o.context, o.PaymentsConfirmPaymentHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/products"] = admin_products.NewCreateProduct(o.context, o.AdminProductsCreateProductHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/products/{id}"] = admin_products.NewDeleteProduct(o.context, o.AdminProductsDeleteProductHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/shipping/addresses/{id}"] = shipping.NewDeleteShippingAddress(o.context, o.ShippingDeleteShippingAddressHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/users/{id}"] = admin_users.NewDeleteUser(o.context, o.AdminUsersDeleteUserHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/cart"] = cart.NewGetCart(o.context, o.CartGetCartHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/orders/{id}"] = orders.NewGetOrder(o.context, o.OrdersGetOrderHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/payments/{id}"] = payments.NewGetPayment(o.context, o.PaymentsGetPaymentHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users/{id}"] = admin_users.NewGetUser(o.context, o.AdminUsersGetUserHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users/me"] = users.NewGetUserProfile(o.context, o.UsersGetUserProfileHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/payments/initiate"] = payments.NewInitiatePayment(o.context, o.PaymentsInitiatePaymentHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/orders"] = orders.NewListOrders(o.context, o.OrdersListOrdersHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/shipping/addresses"] = shipping.NewListShippingAddresses(o.context, o.ShippingListShippingAddressesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/shipping/options"] = shipping.NewListShippingOptions(o.context, o.ShippingListShippingOptionsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users"] = admin_users.NewListUsers(o.context, o.AdminUsersListUsersHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/auth/login"] = users.NewLoginUser(o.context, o.UsersLoginUserHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/orders"] = orders.NewPlaceOrder(o.context, o.OrdersPlaceOrderHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/payments/{id}/refund"] = payments.NewRefundPayment(o.context, o.PaymentsRefundPaymentHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/auth/register"] = users.NewRegisterUser(o.context, o.UsersRegisterUserHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/auth/forgot-password"] = users.NewRequestPasswordReset(o.context, o.UsersRequestPasswordResetHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/auth/reset-password"] = users.NewResetPassword(o.context, o.UsersResetPasswordHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/shipping/track/{orderId}"] = shipping.NewTrackShipment(o.context, o.ShippingTrackShipmentHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/cart"] = cart.NewUpdateCartItem(o.context, o.CartUpdateCartItemHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/products/{id}"] = admin_products.NewUpdateProduct(o.context, o.AdminProductsUpdateProductHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/shipping/addresses/{id}"] = shipping.NewUpdateShippingAddress(o.context, o.ShippingUpdateShippingAddressHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/users/{id}"] = admin_users.NewUpdateUser(o.context, o.AdminUsersUpdateUserHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/users/me"] = users.NewUpdateUserProfile(o.context, o.UsersUpdateUserProfileHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *AdronmeCodeAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *AdronmeCodeAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *AdronmeCodeAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *AdronmeCodeAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *AdronmeCodeAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
