// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Adornme",
    "version": "1.0.0"
  },
  "paths": {
    "/auth/forgot-password": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "summary": "Request password reset",
        "operationId": "requestPasswordReset",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ForgotPasswordRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Password reset email sent"
          },
          "400": {
            "description": "Invalid email",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "summary": "Login user",
        "operationId": "loginUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login successful",
            "schema": {
              "$ref": "#/definitions/AuthResponse"
            }
          },
          "401": {
            "description": "Invalid credentials",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/auth/register": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "summary": "Register a new user",
        "operationId": "registerUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RegisterRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User registered successfully",
            "schema": {
              "$ref": "#/definitions/AuthResponse"
            }
          },
          "400": {
            "description": "Validation error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/auth/reset-password": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "summary": "Reset password",
        "operationId": "resetPassword",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ResetPasswordRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Password reset successful"
          },
          "400": {
            "description": "Invalid or expired token",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/cart": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Get current user's cart",
        "operationId": "getCart",
        "responses": {
          "200": {
            "description": "Current shopping cart",
            "schema": {
              "$ref": "#/definitions/Cart"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Update item quantity in cart",
        "operationId": "updateCartItem",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CartItemUpdateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Cart updated",
            "schema": {
              "$ref": "#/definitions/Cart"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Add item to cart",
        "operationId": "addItemToCart",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CartItemRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Item added to cart",
            "schema": {
              "$ref": "#/definitions/Cart"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Clear cart",
        "operationId": "clearCart",
        "responses": {
          "204": {
            "description": "Cart cleared"
          }
        }
      }
    },
    "/health": {
      "get": {
        "description": "Returns the overall system health status along with the health, uptime, and latency of individual dependencies like Redis, MongoDB, PostgreSQL, OpenSearch, and MinIO.\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "System"
        ],
        "summary": "Health check endpoint",
        "operationId": "getHealth",
        "responses": {
          "200": {
            "description": "Adornme Service health details",
            "schema": {
              "type": "object",
              "properties": {
                "dependencies": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "object",
                    "properties": {
                      "errorMessage": {
                        "description": "Error while checking dependencies",
                        "type": "string",
                        "example": "errorMessage"
                      },
                      "lastChecked": {
                        "description": "Time when the dependency was last checked",
                        "type": "string",
                        "format": "date-time",
                        "example": "2025-11-09T17:25:30Z"
                      },
                      "latencyMs": {
                        "description": "Response latency in milliseconds",
                        "type": "number",
                        "format": "float",
                        "example": 12.34
                      },
                      "status": {
                        "description": "Health status of the dependency",
                        "type": "string",
                        "example": "healthy"
                      },
                      "uptime": {
                        "description": "How long the dependency has been up",
                        "type": "string",
                        "example": "48h12m45s"
                      }
                    }
                  },
                  "example": {
                    "minio": {
                      "lastChecked": "2025-11-09T17:25:30Z",
                      "latencyMs": 7.3,
                      "status": "healthy",
                      "uptime": "60h08m17s"
                    },
                    "mongodb": {
                      "lastChecked": "2025-11-09T17:25:30Z",
                      "latencyMs": 5.1,
                      "status": "healthy",
                      "uptime": "35h59m11s"
                    },
                    "opensearch": {
                      "lastChecked": "2025-11-09T17:25:30Z",
                      "latencyMs": 4.6,
                      "status": "healthy",
                      "uptime": "71h44m21s"
                    },
                    "postgres": {
                      "lastChecked": "2025-11-09T17:25:30Z",
                      "latencyMs": 3.8,
                      "status": "healthy",
                      "uptime": "72h14m03s"
                    },
                    "redis": {
                      "lastChecked": "2025-11-09T17:25:30Z",
                      "latencyMs": 2.4,
                      "status": "healthy",
                      "uptime": "36h42m01s"
                    }
                  }
                },
                "description": {
                  "description": "Human-readable summary of the system health",
                  "type": "string",
                  "example": "All dependencies are healthy and running smoothly"
                },
                "status": {
                  "description": "Overall system status (ok, degraded, or down)",
                  "type": "string",
                  "example": "ok"
                },
                "timestamp": {
                  "description": "UTC timestamp when the health check was performed",
                  "type": "string",
                  "format": "date-time",
                  "example": "2025-11-09T17:27:57Z"
                },
                "uptime": {
                  "description": "Application uptime since last start",
                  "type": "string",
                  "example": "72h35m10s"
                }
              }
            }
          }
        }
      }
    },
    "/orders": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Orders"
        ],
        "summary": "List user's orders",
        "operationId": "listOrders",
        "parameters": [
          {
            "type": "integer",
            "default": 1,
            "name": "page",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 10,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of orders",
            "schema": {
              "$ref": "#/definitions/OrderListResponse"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Orders"
        ],
        "summary": "Place an order from cart",
        "operationId": "placeOrder",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/OrderCreateRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Order placed successfully",
            "schema": {
              "$ref": "#/definitions/Order"
            }
          },
          "400": {
            "description": "Invalid order request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/orders/{id}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Orders"
        ],
        "summary": "Get order details",
        "operationId": "getOrder",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Order details",
            "schema": {
              "$ref": "#/definitions/Order"
            }
          },
          "404": {
            "description": "Order not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/payments/initiate": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Payments"
        ],
        "summary": "Initiate a new payment",
        "operationId": "initiatePayment",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PaymentInitiateRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Payment initiated",
            "schema": {
              "$ref": "#/definitions/PaymentInitiateResponse"
            }
          },
          "400": {
            "description": "Invalid request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/payments/{id}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Payments"
        ],
        "summary": "Get payment details",
        "operationId": "getPayment",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Payment details",
            "schema": {
              "$ref": "#/definitions/Payment"
            }
          },
          "404": {
            "description": "Payment not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/payments/{id}/confirm": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Confirm a payment",
        "operationId": "confirmPayment",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PaymentConfirmRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Payment confirmed",
            "schema": {
              "$ref": "#/definitions/Payment"
            }
          },
          "400": {
            "description": "Invalid confirmation data",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/payments/{id}/refund": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Payments"
        ],
        "summary": "Refund a payment",
        "operationId": "refundPayment",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RefundRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Refund processed",
            "schema": {
              "$ref": "#/definitions/Payment"
            }
          },
          "400": {
            "description": "Invalid refund request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "404": {
            "description": "Payment not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/products": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "AdminProducts"
        ],
        "summary": "Create a new product",
        "operationId": "createProduct",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProductCreateRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Product created successfully"
          },
          "400": {
            "description": "Validation error"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/products/{id}": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "AdminProducts"
        ],
        "summary": "Update a product",
        "operationId": "updateProduct",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProductUpdateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Product updated"
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "AdminProducts"
        ],
        "summary": "Delete a product",
        "operationId": "deleteProduct",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Product deleted"
          }
        }
      }
    },
    "/shipping/addresses": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Shipping"
        ],
        "summary": "Get all addresses for logged-in user",
        "operationId": "listShippingAddresses",
        "responses": {
          "200": {
            "description": "List of user addresses",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Address"
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Shipping"
        ],
        "summary": "Add a new shipping address",
        "operationId": "addShippingAddress",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AddressCreateRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Address added successfully",
            "schema": {
              "$ref": "#/definitions/Address"
            }
          },
          "400": {
            "description": "Validation error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/shipping/addresses/{id}": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Shipping"
        ],
        "summary": "Update a shipping address",
        "operationId": "updateShippingAddress",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AddressUpdateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Address updated",
            "schema": {
              "$ref": "#/definitions/Address"
            }
          },
          "404": {
            "description": "Address not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Shipping"
        ],
        "summary": "Delete a shipping address",
        "operationId": "deleteShippingAddress",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Address deleted"
          },
          "404": {
            "description": "Address not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/shipping/options": {
      "get": {
        "tags": [
          "Shipping"
        ],
        "summary": "Get available shipping options",
        "operationId": "listShippingOptions",
        "responses": {
          "200": {
            "description": "List of shipping options",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ShippingOption"
              }
            }
          }
        }
      }
    },
    "/shipping/track/{orderId}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Shipping"
        ],
        "summary": "Track shipment for an order",
        "operationId": "trackShipment",
        "parameters": [
          {
            "type": "integer",
            "name": "orderId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Shipment tracking details",
            "schema": {
              "$ref": "#/definitions/Tracking"
            }
          },
          "404": {
            "description": "Order or shipment not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "AdminUsers"
        ],
        "summary": "List all users",
        "operationId": "listUsers",
        "parameters": [
          {
            "type": "integer",
            "default": 1,
            "name": "page",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 20,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of users"
          }
        }
      }
    },
    "/users/me": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "summary": "Get logged-in user profile",
        "operationId": "getUserProfile",
        "responses": {
          "200": {
            "description": "User profile details",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "summary": "Update logged-in user profile",
        "operationId": "updateUserProfile",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserUpdateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Profile updated successfully",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Validation error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "AdminUsers"
        ],
        "summary": "Get user details",
        "operationId": "getUser",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "User details"
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "AdminUsers"
        ],
        "summary": "Update user info",
        "operationId": "updateUser",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserUpdateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User updated"
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "AdminUsers"
        ],
        "summary": "Delete a user",
        "operationId": "deleteUser",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "User deleted"
          }
        }
      }
    }
  },
  "definitions": {
    "Address": {
      "description": "Represents a user shipping address.",
      "type": "object",
      "required": [
        "id",
        "userId",
        "addressLine1",
        "city",
        "state",
        "zip",
        "country"
      ],
      "properties": {
        "addressLine1": {
          "type": "string"
        },
        "addressLine2": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "integer"
        },
        "state": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        },
        "userId": {
          "type": "integer"
        },
        "zip": {
          "type": "string"
        }
      }
    },
    "AddressCreateRequest": {
      "description": "Payload to add a new address.",
      "type": "object",
      "required": [
        "addressLine1",
        "city",
        "state",
        "zip",
        "country"
      ],
      "properties": {
        "addressLine1": {
          "type": "string"
        },
        "addressLine2": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "zip": {
          "type": "string"
        }
      }
    },
    "AddressUpdateRequest": {
      "description": "Payload to update an existing address.",
      "type": "object",
      "properties": {
        "addressLine1": {
          "type": "string"
        },
        "addressLine2": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "zip": {
          "type": "string"
        }
      }
    },
    "AuthResponse": {
      "description": "Response containing JWT token and user details after login.",
      "type": "object",
      "required": [
        "token",
        "user"
      ],
      "properties": {
        "refreshToken": {
          "type": "string"
        },
        "token": {
          "type": "string",
          "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        },
        "user": {
          "$ref": "#/definitions/User"
        }
      }
    },
    "Cart": {
      "description": "Shopping cart belonging to a user.",
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CartItem"
          }
        },
        "totalPrice": {
          "type": "number",
          "format": "float",
          "example": 2999.5
        }
      }
    },
    "CartItem": {
      "description": "An item inside the shopping cart.",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "Gold Ring"
        },
        "price": {
          "type": "number",
          "format": "float",
          "example": 1499.75
        },
        "productId": {
          "type": "integer",
          "example": 101
        },
        "quantity": {
          "type": "integer",
          "example": 2
        },
        "subtotal": {
          "type": "number",
          "format": "float",
          "example": 2999.5
        }
      }
    },
    "CartItemRequest": {
      "description": "Payload to add a product to cart.",
      "type": "object",
      "required": [
        "productId",
        "quantity"
      ],
      "properties": {
        "productId": {
          "type": "integer"
        },
        "quantity": {
          "type": "integer",
          "minimum": 1
        }
      }
    },
    "CartItemUpdateRequest": {
      "description": "Payload to update cart item quantity.",
      "type": "object",
      "required": [
        "productId",
        "quantity"
      ],
      "properties": {
        "productId": {
          "type": "integer"
        },
        "quantity": {
          "type": "integer",
          "minimum": 1
        }
      }
    },
    "ErrorResponse": {
      "description": "Standard error response.",
      "type": "object",
      "required": [
        "error",
        "message"
      ],
      "properties": {
        "error": {
          "type": "string",
          "example": "BadRequest"
        },
        "message": {
          "type": "string",
          "example": "Invalid request parameters"
        }
      }
    },
    "ForgotPasswordRequest": {
      "description": "Request to initiate password reset.",
      "type": "object",
      "required": [
        "email"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "example": "paras@example.com"
        }
      }
    },
    "LoginRequest": {
      "description": "Payload to authenticate a user.",
      "type": "object",
      "required": [
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "example": "paras@example.com"
        },
        "password": {
          "type": "string",
          "example": "strongPassword123"
        }
      }
    },
    "Order": {
      "description": "Represents a purchase order.",
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "integer",
          "example": 5001
        },
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CartItem"
          }
        },
        "status": {
          "type": "string",
          "enum": [
            "pending",
            "paid",
            "shipped",
            "delivered",
            "cancelled"
          ],
          "example": "pending"
        },
        "totalPrice": {
          "type": "number",
          "format": "float",
          "example": 2999.5
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        },
        "userId": {
          "type": "integer",
          "example": 101
        }
      }
    },
    "OrderCreateRequest": {
      "description": "Request to create a new order.",
      "type": "object",
      "required": [
        "shippingAddressId",
        "paymentMethod"
      ],
      "properties": {
        "paymentMethod": {
          "type": "string",
          "enum": [
            "cod",
            "card",
            "netbanking",
            "upi"
          ],
          "example": "upi"
        },
        "shippingAddressId": {
          "type": "integer",
          "example": 2001
        }
      }
    },
    "OrderListResponse": {
      "description": "Paginated list of orders.",
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Order"
          }
        },
        "limit": {
          "type": "integer"
        },
        "page": {
          "type": "integer"
        },
        "total": {
          "type": "integer"
        }
      }
    },
    "Payment": {
      "description": "Represents a payment transaction.",
      "type": "object",
      "properties": {
        "amount": {
          "type": "number",
          "format": "float"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "currency": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "orderId": {
          "type": "integer"
        },
        "status": {
          "type": "string"
        },
        "transactionId": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        },
        "userId": {
          "type": "integer"
        }
      }
    },
    "PaymentConfirmRequest": {
      "description": "Request to confirm a payment.",
      "type": "object",
      "required": [
        "transactionId",
        "status"
      ],
      "properties": {
        "signature": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "transactionId": {
          "type": "string"
        }
      }
    },
    "PaymentInitiateRequest": {
      "description": "Request to initiate a payment.",
      "type": "object",
      "required": [
        "orderId",
        "method"
      ],
      "properties": {
        "method": {
          "type": "string"
        },
        "orderId": {
          "type": "integer"
        }
      }
    },
    "PaymentInitiateResponse": {
      "description": "Response after payment initiation.",
      "type": "object",
      "properties": {
        "gatewayUrl": {
          "type": "string"
        },
        "paymentId": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "Principal": {
      "type": "object",
      "properties": {
        "authEmail": {
          "type": "string"
        },
        "authId": {
          "type": "string"
        },
        "authName": {
          "type": "string"
        },
        "crn": {
          "description": "Workaround for AT event tracker",
          "type": "string"
        },
        "region": {
          "description": "Workaround for API's not having region in their context",
          "type": "string"
        },
        "token": {
          "description": "OAuth2 Token",
          "$ref": "#/definitions/Token"
        },
        "userAccess": {
          "description": "User Access",
          "$ref": "#/definitions/UserAccess"
        },
        "userEmail": {
          "description": "Email of User",
          "type": "string"
        },
        "userID": {
          "description": "ID of User",
          "type": "string"
        },
        "userInfo": {
          "description": "Object that keeps track of user authentication info",
          "$ref": "#/definitions/UserAuthenticationInfo"
        }
      }
    },
    "Product": {
      "description": "Represents a product available in the catalog.",
      "type": "object",
      "required": [
        "id",
        "name",
        "price",
        "stock",
        "categoryId"
      ],
      "properties": {
        "categoryId": {
          "type": "integer",
          "example": 5
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string",
          "example": "22K pure gold necklace with intricate design"
        },
        "id": {
          "type": "integer",
          "example": 101
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "https://cdn.adornme.com/products/101-1.jpg",
            "https://cdn.adornme.com/products/101-2.jpg"
          ]
        },
        "name": {
          "type": "string",
          "example": "Gold Necklace"
        },
        "price": {
          "type": "number",
          "format": "float",
          "example": 14999.99
        },
        "stock": {
          "type": "integer",
          "example": 20
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "ProductCreateRequest": {
      "description": "Request to create a new product.",
      "type": "object",
      "required": [
        "name",
        "price",
        "stock",
        "categoryId"
      ],
      "properties": {
        "categoryId": {
          "type": "integer"
        },
        "description": {
          "type": "string"
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "type": "string"
        },
        "price": {
          "type": "number",
          "format": "float"
        },
        "stock": {
          "type": "integer"
        }
      }
    },
    "ProductListResponse": {
      "description": "Paginated list of products.",
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Product"
          }
        },
        "limit": {
          "type": "integer",
          "example": 20
        },
        "page": {
          "type": "integer",
          "example": 1
        },
        "total": {
          "type": "integer",
          "example": 100
        }
      }
    },
    "ProductUpdateRequest": {
      "description": "Request to update product details.",
      "type": "object",
      "properties": {
        "categoryId": {
          "type": "integer"
        },
        "description": {
          "type": "string"
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "type": "string"
        },
        "price": {
          "type": "number",
          "format": "float"
        },
        "stock": {
          "type": "integer"
        }
      }
    },
    "RefundRequest": {
      "description": "Request to process a refund.",
      "type": "object",
      "required": [
        "amount",
        "reason"
      ],
      "properties": {
        "amount": {
          "type": "number",
          "format": "float"
        },
        "reason": {
          "type": "string"
        }
      }
    },
    "RegisterRequest": {
      "description": "Payload to register a new user.",
      "type": "object",
      "required": [
        "name",
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "example": "paras@example.com"
        },
        "name": {
          "type": "string",
          "example": "Paras Jain"
        },
        "password": {
          "type": "string",
          "example": "strongPassword123"
        },
        "phone": {
          "type": "string",
          "example": 919876543210
        }
      }
    },
    "ResetPasswordRequest": {
      "description": "Request to reset password with token.",
      "type": "object",
      "required": [
        "token",
        "newPassword"
      ],
      "properties": {
        "newPassword": {
          "type": "string",
          "example": "strongNewPassword123"
        },
        "token": {
          "type": "string",
          "example": "reset_token_xyz"
        }
      }
    },
    "ShippingOption": {
      "description": "Represents available shipping option.",
      "type": "object",
      "properties": {
        "cost": {
          "type": "number",
          "format": "float"
        },
        "estimatedDays": {
          "type": "integer"
        },
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "Token": {
      "type": "object",
      "required": [
        "accessToken",
        "type",
        "refreshToken",
        "expires"
      ],
      "properties": {
        "accessToken": {
          "description": "AccessToken",
          "type": "string"
        },
        "expires": {
          "description": "Token Expires",
          "type": "string",
          "format": "date-time"
        },
        "refreshToken": {
          "description": "Refresh Token",
          "type": "string"
        },
        "type": {
          "description": "Token Type",
          "type": "string"
        }
      }
    },
    "Tracking": {
      "description": "Represents order tracking details.",
      "type": "object",
      "properties": {
        "carrier": {
          "type": "string"
        },
        "estimatedDelivery": {
          "type": "string",
          "format": "date-time"
        },
        "orderId": {
          "type": "integer"
        },
        "status": {
          "type": "string",
          "enum": [
            "pending",
            "dispatched",
            "in_transit",
            "delivered",
            "cancelled"
          ]
        },
        "trackingNumber": {
          "type": "string"
        }
      }
    },
    "User": {
      "description": "Represents a registered user in the system.",
      "type": "object",
      "required": [
        "id",
        "email",
        "name"
      ],
      "properties": {
        "createdAt": {
          "description": "User creation timestamp",
          "type": "string",
          "format": "date-time"
        },
        "email": {
          "description": "User email address",
          "type": "string",
          "format": "email",
          "example": "paras@example.com"
        },
        "id": {
          "description": "Unique user identifier",
          "type": "integer",
          "example": 101
        },
        "name": {
          "description": "Full name of the user",
          "type": "string",
          "example": "Paras Jain"
        },
        "password": {
          "description": "Password of user",
          "type": "string"
        },
        "phone": {
          "description": "User phone number",
          "type": "string",
          "example": 919876543210
        },
        "updatedAt": {
          "description": "Last update timestamp",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "UserAccess": {
      "description": "Keeps tracks of individual user's access and roles",
      "type": "object",
      "properties": {
        "_id": {
          "description": "User ID",
          "type": "string",
          "x-go-custom-tag": "datastore:\"id\"",
          "x-go-name": "UserID"
        },
        "_rev": {
          "type": "string",
          "x-go-custom-tag": "datastore:\"-\""
        },
        "baseRole": {
          "description": "Base Role for this User",
          "type": "string",
          "default": "user-readonly",
          "enum": [
            "user-admin",
            "user-readonly",
            "service-admin",
            "service-readonly",
            "disabled",
            "pending"
          ],
          "x-go-custom-tag": "datastore:\"baseRole\"",
          "x-isnullable": false
        },
        "memberOf": {
          "description": "Member of (Tenants)",
          "type": "array",
          "items": {
            "type": "string"
          },
          "x-go-custom-tag": "datastore:\"memberOf\""
        },
        "notes": {
          "description": "Notes for development (not used internally)",
          "type": "string",
          "x-go-custom-tag": "datastore:\"notes,noindex,omitempty\""
        }
      }
    },
    "UserAuthenticationInfo": {
      "type": "object",
      "properties": {
        "credentialType": {
          "description": "Workaround for AT event tracker",
          "type": "string"
        }
      }
    },
    "UserUpdateRequest": {
      "description": "Payload to update user profile.",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "Paras Jain"
        },
        "phone": {
          "type": "string",
          "example": 919876543210
        }
      }
    }
  },
  "securityDefinitions": {
    "apiKey": {
      "type": "apiKey",
      "name": "x-api-key",
      "in": "header"
    },
    "basicAuth": {
      "type": "basic"
    },
    "bearerAuth": {
      "description": "Bearer token for authentication",
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Adornme",
    "version": "1.0.0"
  },
  "paths": {
    "/auth/forgot-password": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "summary": "Request password reset",
        "operationId": "requestPasswordReset",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ForgotPasswordRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Password reset email sent"
          },
          "400": {
            "description": "Invalid email",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "summary": "Login user",
        "operationId": "loginUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login successful",
            "schema": {
              "$ref": "#/definitions/AuthResponse"
            }
          },
          "401": {
            "description": "Invalid credentials",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/auth/register": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "summary": "Register a new user",
        "operationId": "registerUser",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RegisterRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User registered successfully",
            "schema": {
              "$ref": "#/definitions/AuthResponse"
            }
          },
          "400": {
            "description": "Validation error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/auth/reset-password": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "summary": "Reset password",
        "operationId": "resetPassword",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ResetPasswordRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Password reset successful"
          },
          "400": {
            "description": "Invalid or expired token",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/cart": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Get current user's cart",
        "operationId": "getCart",
        "responses": {
          "200": {
            "description": "Current shopping cart",
            "schema": {
              "$ref": "#/definitions/Cart"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Update item quantity in cart",
        "operationId": "updateCartItem",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CartItemUpdateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Cart updated",
            "schema": {
              "$ref": "#/definitions/Cart"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Add item to cart",
        "operationId": "addItemToCart",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CartItemRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Item added to cart",
            "schema": {
              "$ref": "#/definitions/Cart"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Cart"
        ],
        "summary": "Clear cart",
        "operationId": "clearCart",
        "responses": {
          "204": {
            "description": "Cart cleared"
          }
        }
      }
    },
    "/health": {
      "get": {
        "description": "Returns the overall system health status along with the health, uptime, and latency of individual dependencies like Redis, MongoDB, PostgreSQL, OpenSearch, and MinIO.\n",
        "produces": [
          "application/json"
        ],
        "tags": [
          "System"
        ],
        "summary": "Health check endpoint",
        "operationId": "getHealth",
        "responses": {
          "200": {
            "description": "Adornme Service health details",
            "schema": {
              "type": "object",
              "properties": {
                "dependencies": {
                  "type": "object",
                  "additionalProperties": {
                    "$ref": "#/definitions/DependenciesAnon"
                  },
                  "example": {
                    "minio": {
                      "lastChecked": "2025-11-09T17:25:30Z",
                      "latencyMs": 7.3,
                      "status": "healthy",
                      "uptime": "60h08m17s"
                    },
                    "mongodb": {
                      "lastChecked": "2025-11-09T17:25:30Z",
                      "latencyMs": 5.1,
                      "status": "healthy",
                      "uptime": "35h59m11s"
                    },
                    "opensearch": {
                      "lastChecked": "2025-11-09T17:25:30Z",
                      "latencyMs": 4.6,
                      "status": "healthy",
                      "uptime": "71h44m21s"
                    },
                    "postgres": {
                      "lastChecked": "2025-11-09T17:25:30Z",
                      "latencyMs": 3.8,
                      "status": "healthy",
                      "uptime": "72h14m03s"
                    },
                    "redis": {
                      "lastChecked": "2025-11-09T17:25:30Z",
                      "latencyMs": 2.4,
                      "status": "healthy",
                      "uptime": "36h42m01s"
                    }
                  }
                },
                "description": {
                  "description": "Human-readable summary of the system health",
                  "type": "string",
                  "example": "All dependencies are healthy and running smoothly"
                },
                "status": {
                  "description": "Overall system status (ok, degraded, or down)",
                  "type": "string",
                  "example": "ok"
                },
                "timestamp": {
                  "description": "UTC timestamp when the health check was performed",
                  "type": "string",
                  "format": "date-time",
                  "example": "2025-11-09T17:27:57Z"
                },
                "uptime": {
                  "description": "Application uptime since last start",
                  "type": "string",
                  "example": "72h35m10s"
                }
              }
            }
          }
        }
      }
    },
    "/orders": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Orders"
        ],
        "summary": "List user's orders",
        "operationId": "listOrders",
        "parameters": [
          {
            "type": "integer",
            "default": 1,
            "name": "page",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 10,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated list of orders",
            "schema": {
              "$ref": "#/definitions/OrderListResponse"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Orders"
        ],
        "summary": "Place an order from cart",
        "operationId": "placeOrder",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/OrderCreateRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Order placed successfully",
            "schema": {
              "$ref": "#/definitions/Order"
            }
          },
          "400": {
            "description": "Invalid order request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/orders/{id}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Orders"
        ],
        "summary": "Get order details",
        "operationId": "getOrder",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Order details",
            "schema": {
              "$ref": "#/definitions/Order"
            }
          },
          "404": {
            "description": "Order not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/payments/initiate": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Payments"
        ],
        "summary": "Initiate a new payment",
        "operationId": "initiatePayment",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PaymentInitiateRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Payment initiated",
            "schema": {
              "$ref": "#/definitions/PaymentInitiateResponse"
            }
          },
          "400": {
            "description": "Invalid request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/payments/{id}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Payments"
        ],
        "summary": "Get payment details",
        "operationId": "getPayment",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Payment details",
            "schema": {
              "$ref": "#/definitions/Payment"
            }
          },
          "404": {
            "description": "Payment not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/payments/{id}/confirm": {
      "post": {
        "tags": [
          "Payments"
        ],
        "summary": "Confirm a payment",
        "operationId": "confirmPayment",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PaymentConfirmRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Payment confirmed",
            "schema": {
              "$ref": "#/definitions/Payment"
            }
          },
          "400": {
            "description": "Invalid confirmation data",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/payments/{id}/refund": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Payments"
        ],
        "summary": "Refund a payment",
        "operationId": "refundPayment",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RefundRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Refund processed",
            "schema": {
              "$ref": "#/definitions/Payment"
            }
          },
          "400": {
            "description": "Invalid refund request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "404": {
            "description": "Payment not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/products": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "AdminProducts"
        ],
        "summary": "Create a new product",
        "operationId": "createProduct",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProductCreateRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Product created successfully"
          },
          "400": {
            "description": "Validation error"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/products/{id}": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "AdminProducts"
        ],
        "summary": "Update a product",
        "operationId": "updateProduct",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProductUpdateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Product updated"
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "AdminProducts"
        ],
        "summary": "Delete a product",
        "operationId": "deleteProduct",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Product deleted"
          }
        }
      }
    },
    "/shipping/addresses": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Shipping"
        ],
        "summary": "Get all addresses for logged-in user",
        "operationId": "listShippingAddresses",
        "responses": {
          "200": {
            "description": "List of user addresses",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Address"
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Shipping"
        ],
        "summary": "Add a new shipping address",
        "operationId": "addShippingAddress",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AddressCreateRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Address added successfully",
            "schema": {
              "$ref": "#/definitions/Address"
            }
          },
          "400": {
            "description": "Validation error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/shipping/addresses/{id}": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Shipping"
        ],
        "summary": "Update a shipping address",
        "operationId": "updateShippingAddress",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AddressUpdateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Address updated",
            "schema": {
              "$ref": "#/definitions/Address"
            }
          },
          "404": {
            "description": "Address not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Shipping"
        ],
        "summary": "Delete a shipping address",
        "operationId": "deleteShippingAddress",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Address deleted"
          },
          "404": {
            "description": "Address not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/shipping/options": {
      "get": {
        "tags": [
          "Shipping"
        ],
        "summary": "Get available shipping options",
        "operationId": "listShippingOptions",
        "responses": {
          "200": {
            "description": "List of shipping options",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ShippingOption"
              }
            }
          }
        }
      }
    },
    "/shipping/track/{orderId}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Shipping"
        ],
        "summary": "Track shipment for an order",
        "operationId": "trackShipment",
        "parameters": [
          {
            "type": "integer",
            "name": "orderId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Shipment tracking details",
            "schema": {
              "$ref": "#/definitions/Tracking"
            }
          },
          "404": {
            "description": "Order or shipment not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "AdminUsers"
        ],
        "summary": "List all users",
        "operationId": "listUsers",
        "parameters": [
          {
            "type": "integer",
            "default": 1,
            "name": "page",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 20,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of users"
          }
        }
      }
    },
    "/users/me": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "summary": "Get logged-in user profile",
        "operationId": "getUserProfile",
        "responses": {
          "200": {
            "description": "User profile details",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Users"
        ],
        "summary": "Update logged-in user profile",
        "operationId": "updateUserProfile",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserUpdateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Profile updated successfully",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Validation error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "AdminUsers"
        ],
        "summary": "Get user details",
        "operationId": "getUser",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "User details"
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "AdminUsers"
        ],
        "summary": "Update user info",
        "operationId": "updateUser",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserUpdateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User updated"
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "AdminUsers"
        ],
        "summary": "Delete a user",
        "operationId": "deleteUser",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "User deleted"
          }
        }
      }
    }
  },
  "definitions": {
    "Address": {
      "description": "Represents a user shipping address.",
      "type": "object",
      "required": [
        "id",
        "userId",
        "addressLine1",
        "city",
        "state",
        "zip",
        "country"
      ],
      "properties": {
        "addressLine1": {
          "type": "string"
        },
        "addressLine2": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "integer"
        },
        "state": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        },
        "userId": {
          "type": "integer"
        },
        "zip": {
          "type": "string"
        }
      }
    },
    "AddressCreateRequest": {
      "description": "Payload to add a new address.",
      "type": "object",
      "required": [
        "addressLine1",
        "city",
        "state",
        "zip",
        "country"
      ],
      "properties": {
        "addressLine1": {
          "type": "string"
        },
        "addressLine2": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "zip": {
          "type": "string"
        }
      }
    },
    "AddressUpdateRequest": {
      "description": "Payload to update an existing address.",
      "type": "object",
      "properties": {
        "addressLine1": {
          "type": "string"
        },
        "addressLine2": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "zip": {
          "type": "string"
        }
      }
    },
    "AuthResponse": {
      "description": "Response containing JWT token and user details after login.",
      "type": "object",
      "required": [
        "token",
        "user"
      ],
      "properties": {
        "refreshToken": {
          "type": "string"
        },
        "token": {
          "type": "string",
          "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        },
        "user": {
          "$ref": "#/definitions/User"
        }
      }
    },
    "Cart": {
      "description": "Shopping cart belonging to a user.",
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CartItem"
          }
        },
        "totalPrice": {
          "type": "number",
          "format": "float",
          "example": 2999.5
        }
      }
    },
    "CartItem": {
      "description": "An item inside the shopping cart.",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "Gold Ring"
        },
        "price": {
          "type": "number",
          "format": "float",
          "example": 1499.75
        },
        "productId": {
          "type": "integer",
          "example": 101
        },
        "quantity": {
          "type": "integer",
          "example": 2
        },
        "subtotal": {
          "type": "number",
          "format": "float",
          "example": 2999.5
        }
      }
    },
    "CartItemRequest": {
      "description": "Payload to add a product to cart.",
      "type": "object",
      "required": [
        "productId",
        "quantity"
      ],
      "properties": {
        "productId": {
          "type": "integer"
        },
        "quantity": {
          "type": "integer",
          "minimum": 1
        }
      }
    },
    "CartItemUpdateRequest": {
      "description": "Payload to update cart item quantity.",
      "type": "object",
      "required": [
        "productId",
        "quantity"
      ],
      "properties": {
        "productId": {
          "type": "integer"
        },
        "quantity": {
          "type": "integer",
          "minimum": 1
        }
      }
    },
    "DependenciesAnon": {
      "type": "object",
      "properties": {
        "errorMessage": {
          "description": "Error while checking dependencies",
          "type": "string",
          "example": "errorMessage"
        },
        "lastChecked": {
          "description": "Time when the dependency was last checked",
          "type": "string",
          "format": "date-time",
          "example": "2025-11-09T17:25:30Z"
        },
        "latencyMs": {
          "description": "Response latency in milliseconds",
          "type": "number",
          "format": "float",
          "example": 12.34
        },
        "status": {
          "description": "Health status of the dependency",
          "type": "string",
          "example": "healthy"
        },
        "uptime": {
          "description": "How long the dependency has been up",
          "type": "string",
          "example": "48h12m45s"
        }
      }
    },
    "ErrorResponse": {
      "description": "Standard error response.",
      "type": "object",
      "required": [
        "error",
        "message"
      ],
      "properties": {
        "error": {
          "type": "string",
          "example": "BadRequest"
        },
        "message": {
          "type": "string",
          "example": "Invalid request parameters"
        }
      }
    },
    "ForgotPasswordRequest": {
      "description": "Request to initiate password reset.",
      "type": "object",
      "required": [
        "email"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "example": "paras@example.com"
        }
      }
    },
    "LoginRequest": {
      "description": "Payload to authenticate a user.",
      "type": "object",
      "required": [
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "example": "paras@example.com"
        },
        "password": {
          "type": "string",
          "example": "strongPassword123"
        }
      }
    },
    "Order": {
      "description": "Represents a purchase order.",
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "integer",
          "example": 5001
        },
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CartItem"
          }
        },
        "status": {
          "type": "string",
          "enum": [
            "pending",
            "paid",
            "shipped",
            "delivered",
            "cancelled"
          ],
          "example": "pending"
        },
        "totalPrice": {
          "type": "number",
          "format": "float",
          "example": 2999.5
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        },
        "userId": {
          "type": "integer",
          "example": 101
        }
      }
    },
    "OrderCreateRequest": {
      "description": "Request to create a new order.",
      "type": "object",
      "required": [
        "shippingAddressId",
        "paymentMethod"
      ],
      "properties": {
        "paymentMethod": {
          "type": "string",
          "enum": [
            "cod",
            "card",
            "netbanking",
            "upi"
          ],
          "example": "upi"
        },
        "shippingAddressId": {
          "type": "integer",
          "example": 2001
        }
      }
    },
    "OrderListResponse": {
      "description": "Paginated list of orders.",
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Order"
          }
        },
        "limit": {
          "type": "integer"
        },
        "page": {
          "type": "integer"
        },
        "total": {
          "type": "integer"
        }
      }
    },
    "Payment": {
      "description": "Represents a payment transaction.",
      "type": "object",
      "properties": {
        "amount": {
          "type": "number",
          "format": "float"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "currency": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "orderId": {
          "type": "integer"
        },
        "status": {
          "type": "string"
        },
        "transactionId": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        },
        "userId": {
          "type": "integer"
        }
      }
    },
    "PaymentConfirmRequest": {
      "description": "Request to confirm a payment.",
      "type": "object",
      "required": [
        "transactionId",
        "status"
      ],
      "properties": {
        "signature": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "transactionId": {
          "type": "string"
        }
      }
    },
    "PaymentInitiateRequest": {
      "description": "Request to initiate a payment.",
      "type": "object",
      "required": [
        "orderId",
        "method"
      ],
      "properties": {
        "method": {
          "type": "string"
        },
        "orderId": {
          "type": "integer"
        }
      }
    },
    "PaymentInitiateResponse": {
      "description": "Response after payment initiation.",
      "type": "object",
      "properties": {
        "gatewayUrl": {
          "type": "string"
        },
        "paymentId": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "Principal": {
      "type": "object",
      "properties": {
        "authEmail": {
          "type": "string"
        },
        "authId": {
          "type": "string"
        },
        "authName": {
          "type": "string"
        },
        "crn": {
          "description": "Workaround for AT event tracker",
          "type": "string"
        },
        "region": {
          "description": "Workaround for API's not having region in their context",
          "type": "string"
        },
        "token": {
          "description": "OAuth2 Token",
          "$ref": "#/definitions/Token"
        },
        "userAccess": {
          "description": "User Access",
          "$ref": "#/definitions/UserAccess"
        },
        "userEmail": {
          "description": "Email of User",
          "type": "string"
        },
        "userID": {
          "description": "ID of User",
          "type": "string"
        },
        "userInfo": {
          "description": "Object that keeps track of user authentication info",
          "$ref": "#/definitions/UserAuthenticationInfo"
        }
      }
    },
    "Product": {
      "description": "Represents a product available in the catalog.",
      "type": "object",
      "required": [
        "id",
        "name",
        "price",
        "stock",
        "categoryId"
      ],
      "properties": {
        "categoryId": {
          "type": "integer",
          "example": 5
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string",
          "example": "22K pure gold necklace with intricate design"
        },
        "id": {
          "type": "integer",
          "example": 101
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "https://cdn.adornme.com/products/101-1.jpg",
            "https://cdn.adornme.com/products/101-2.jpg"
          ]
        },
        "name": {
          "type": "string",
          "example": "Gold Necklace"
        },
        "price": {
          "type": "number",
          "format": "float",
          "example": 14999.99
        },
        "stock": {
          "type": "integer",
          "example": 20
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "ProductCreateRequest": {
      "description": "Request to create a new product.",
      "type": "object",
      "required": [
        "name",
        "price",
        "stock",
        "categoryId"
      ],
      "properties": {
        "categoryId": {
          "type": "integer"
        },
        "description": {
          "type": "string"
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "type": "string"
        },
        "price": {
          "type": "number",
          "format": "float"
        },
        "stock": {
          "type": "integer"
        }
      }
    },
    "ProductListResponse": {
      "description": "Paginated list of products.",
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Product"
          }
        },
        "limit": {
          "type": "integer",
          "example": 20
        },
        "page": {
          "type": "integer",
          "example": 1
        },
        "total": {
          "type": "integer",
          "example": 100
        }
      }
    },
    "ProductUpdateRequest": {
      "description": "Request to update product details.",
      "type": "object",
      "properties": {
        "categoryId": {
          "type": "integer"
        },
        "description": {
          "type": "string"
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "type": "string"
        },
        "price": {
          "type": "number",
          "format": "float"
        },
        "stock": {
          "type": "integer"
        }
      }
    },
    "RefundRequest": {
      "description": "Request to process a refund.",
      "type": "object",
      "required": [
        "amount",
        "reason"
      ],
      "properties": {
        "amount": {
          "type": "number",
          "format": "float"
        },
        "reason": {
          "type": "string"
        }
      }
    },
    "RegisterRequest": {
      "description": "Payload to register a new user.",
      "type": "object",
      "required": [
        "name",
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "example": "paras@example.com"
        },
        "name": {
          "type": "string",
          "example": "Paras Jain"
        },
        "password": {
          "type": "string",
          "example": "strongPassword123"
        },
        "phone": {
          "type": "string",
          "example": 919876543210
        }
      }
    },
    "ResetPasswordRequest": {
      "description": "Request to reset password with token.",
      "type": "object",
      "required": [
        "token",
        "newPassword"
      ],
      "properties": {
        "newPassword": {
          "type": "string",
          "example": "strongNewPassword123"
        },
        "token": {
          "type": "string",
          "example": "reset_token_xyz"
        }
      }
    },
    "ShippingOption": {
      "description": "Represents available shipping option.",
      "type": "object",
      "properties": {
        "cost": {
          "type": "number",
          "format": "float"
        },
        "estimatedDays": {
          "type": "integer"
        },
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "Token": {
      "type": "object",
      "required": [
        "accessToken",
        "type",
        "refreshToken",
        "expires"
      ],
      "properties": {
        "accessToken": {
          "description": "AccessToken",
          "type": "string"
        },
        "expires": {
          "description": "Token Expires",
          "type": "string",
          "format": "date-time"
        },
        "refreshToken": {
          "description": "Refresh Token",
          "type": "string"
        },
        "type": {
          "description": "Token Type",
          "type": "string"
        }
      }
    },
    "Tracking": {
      "description": "Represents order tracking details.",
      "type": "object",
      "properties": {
        "carrier": {
          "type": "string"
        },
        "estimatedDelivery": {
          "type": "string",
          "format": "date-time"
        },
        "orderId": {
          "type": "integer"
        },
        "status": {
          "type": "string",
          "enum": [
            "pending",
            "dispatched",
            "in_transit",
            "delivered",
            "cancelled"
          ]
        },
        "trackingNumber": {
          "type": "string"
        }
      }
    },
    "User": {
      "description": "Represents a registered user in the system.",
      "type": "object",
      "required": [
        "id",
        "email",
        "name"
      ],
      "properties": {
        "createdAt": {
          "description": "User creation timestamp",
          "type": "string",
          "format": "date-time"
        },
        "email": {
          "description": "User email address",
          "type": "string",
          "format": "email",
          "example": "paras@example.com"
        },
        "id": {
          "description": "Unique user identifier",
          "type": "integer",
          "example": 101
        },
        "name": {
          "description": "Full name of the user",
          "type": "string",
          "example": "Paras Jain"
        },
        "password": {
          "description": "Password of user",
          "type": "string"
        },
        "phone": {
          "description": "User phone number",
          "type": "string",
          "example": 919876543210
        },
        "updatedAt": {
          "description": "Last update timestamp",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "UserAccess": {
      "description": "Keeps tracks of individual user's access and roles",
      "type": "object",
      "properties": {
        "_id": {
          "description": "User ID",
          "type": "string",
          "x-go-custom-tag": "datastore:\"id\"",
          "x-go-name": "UserID"
        },
        "_rev": {
          "type": "string",
          "x-go-custom-tag": "datastore:\"-\""
        },
        "baseRole": {
          "description": "Base Role for this User",
          "type": "string",
          "default": "user-readonly",
          "enum": [
            "user-admin",
            "user-readonly",
            "service-admin",
            "service-readonly",
            "disabled",
            "pending"
          ],
          "x-go-custom-tag": "datastore:\"baseRole\"",
          "x-isnullable": false
        },
        "memberOf": {
          "description": "Member of (Tenants)",
          "type": "array",
          "items": {
            "type": "string"
          },
          "x-go-custom-tag": "datastore:\"memberOf\""
        },
        "notes": {
          "description": "Notes for development (not used internally)",
          "type": "string",
          "x-go-custom-tag": "datastore:\"notes,noindex,omitempty\""
        }
      }
    },
    "UserAuthenticationInfo": {
      "type": "object",
      "properties": {
        "credentialType": {
          "description": "Workaround for AT event tracker",
          "type": "string"
        }
      }
    },
    "UserUpdateRequest": {
      "description": "Payload to update user profile.",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "Paras Jain"
        },
        "phone": {
          "type": "string",
          "example": 919876543210
        }
      }
    }
  },
  "securityDefinitions": {
    "apiKey": {
      "type": "apiKey",
      "name": "x-api-key",
      "in": "header"
    },
    "basicAuth": {
      "type": "basic"
    },
    "bearerAuth": {
      "description": "Bearer token for authentication",
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
