// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/AdornmeCode/Carts/models"
)

// GetOrdersOKCode is the HTTP code returned for type GetOrdersOK
const GetOrdersOKCode int = 200

/*
GetOrdersOK Paginated list of orders

swagger:response getOrdersOK
*/
type GetOrdersOK struct {

	/*
	  In: Body
	*/
	Payload *models.OrderListResponse `json:"body,omitempty"`
}

// NewGetOrdersOK creates GetOrdersOK with default headers values
func NewGetOrdersOK() *GetOrdersOK {

	return &GetOrdersOK{}
}

// WithPayload adds the payload to the get orders o k response
func (o *GetOrdersOK) WithPayload(payload *models.OrderListResponse) *GetOrdersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get orders o k response
func (o *GetOrdersOK) SetPayload(payload *models.OrderListResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrdersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
