// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/AdornmeCode/Carts/models"
)

// GetOrdersIDOKCode is the HTTP code returned for type GetOrdersIDOK
const GetOrdersIDOKCode int = 200

/*
GetOrdersIDOK Order details

swagger:response getOrdersIdOK
*/
type GetOrdersIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Order `json:"body,omitempty"`
}

// NewGetOrdersIDOK creates GetOrdersIDOK with default headers values
func NewGetOrdersIDOK() *GetOrdersIDOK {

	return &GetOrdersIDOK{}
}

// WithPayload adds the payload to the get orders Id o k response
func (o *GetOrdersIDOK) WithPayload(payload *models.Order) *GetOrdersIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get orders Id o k response
func (o *GetOrdersIDOK) SetPayload(payload *models.Order) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrdersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOrdersIDNotFoundCode is the HTTP code returned for type GetOrdersIDNotFound
const GetOrdersIDNotFoundCode int = 404

/*
GetOrdersIDNotFound Order not found

swagger:response getOrdersIdNotFound
*/
type GetOrdersIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetOrdersIDNotFound creates GetOrdersIDNotFound with default headers values
func NewGetOrdersIDNotFound() *GetOrdersIDNotFound {

	return &GetOrdersIDNotFound{}
}

// WithPayload adds the payload to the get orders Id not found response
func (o *GetOrdersIDNotFound) WithPayload(payload *models.ErrorResponse) *GetOrdersIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get orders Id not found response
func (o *GetOrdersIDNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOrdersIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
