// Code generated by go-swagger; DO NOT EDIT.

package admin_products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteProductsIDNoContentCode is the HTTP code returned for type DeleteProductsIDNoContent
const DeleteProductsIDNoContentCode int = 204

/*
DeleteProductsIDNoContent Product deleted

swagger:response deleteProductsIdNoContent
*/
type DeleteProductsIDNoContent struct {
}

// NewDeleteProductsIDNoContent creates DeleteProductsIDNoContent with default headers values
func NewDeleteProductsIDNoContent() *DeleteProductsIDNoContent {

	return &DeleteProductsIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteProductsIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
