// Code generated by go-swagger; DO NOT EDIT.

package admin_products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostProductsCreatedCode is the HTTP code returned for type PostProductsCreated
const PostProductsCreatedCode int = 201

/*
PostProductsCreated Product created successfully

swagger:response postProductsCreated
*/
type PostProductsCreated struct {
}

// NewPostProductsCreated creates PostProductsCreated with default headers values
func NewPostProductsCreated() *PostProductsCreated {

	return &PostProductsCreated{}
}

// WriteResponse to the client
func (o *PostProductsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostProductsBadRequestCode is the HTTP code returned for type PostProductsBadRequest
const PostProductsBadRequestCode int = 400

/*
PostProductsBadRequest Validation error

swagger:response postProductsBadRequest
*/
type PostProductsBadRequest struct {
}

// NewPostProductsBadRequest creates PostProductsBadRequest with default headers values
func NewPostProductsBadRequest() *PostProductsBadRequest {

	return &PostProductsBadRequest{}
}

// WriteResponse to the client
func (o *PostProductsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostProductsUnauthorizedCode is the HTTP code returned for type PostProductsUnauthorized
const PostProductsUnauthorizedCode int = 401

/*
PostProductsUnauthorized Unauthorized

swagger:response postProductsUnauthorized
*/
type PostProductsUnauthorized struct {
}

// NewPostProductsUnauthorized creates PostProductsUnauthorized with default headers values
func NewPostProductsUnauthorized() *PostProductsUnauthorized {

	return &PostProductsUnauthorized{}
}

// WriteResponse to the client
func (o *PostProductsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
