// Code generated by go-swagger; DO NOT EDIT.

package admin_products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutProductsIDOKCode is the HTTP code returned for type PutProductsIDOK
const PutProductsIDOKCode int = 200

/*
PutProductsIDOK Product updated

swagger:response putProductsIdOK
*/
type PutProductsIDOK struct {
}

// NewPutProductsIDOK creates PutProductsIDOK with default headers values
func NewPutProductsIDOK() *PutProductsIDOK {

	return &PutProductsIDOK{}
}

// WriteResponse to the client
func (o *PutProductsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
