openapi: 3.0.3
info:
  title: Shipping API
  version: 1.0.0
  description: |
    API specification for managing shipping addresses, shipping options,
    and tracking customer orders.

servers:
  - url: https://api.adornme.com/v1
    description: Production server
  - url: https://staging-api.adornme.com/v1
    description: Staging server

tags:
  - name: Shipping
    description: Manage addresses, shipping options, and track orders

paths:
  /shipping/addresses:
    get:
      summary: Get all addresses for logged-in user
      tags: [Shipping]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of user addresses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Address"
        "401":
          description: Unauthorized

    post:
      summary: Add a new shipping address
      tags: [Shipping]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddressCreateRequest"
      responses:
        "201":
          description: Address added successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Address"
        "400":
          description: Validation error

  /shipping/addresses/{id}:
    put:
      summary: Update a shipping address
      tags: [Shipping]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddressUpdateRequest"
      responses:
        "200":
          description: Address updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Address"
        "404":
          description: Address not found

    delete:
      summary: Delete a shipping address
      tags: [Shipping]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Address deleted
        "404":
          description: Address not found

  /shipping/options:
    get:
      summary: Get available shipping options
      tags: [Shipping]
      responses:
        "200":
          description: List of shipping options
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ShippingOption"

  /shipping/track/{orderId}:
    get:
      summary: Track shipment for an order
      tags: [Shipping]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Shipment tracking details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tracking"
        "404":
          description: Order or shipment not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Address:
      type: object
      required: [id, userId, addressLine1, city, state, zip, country]
      properties:
        id:
          type: integer
          example: 3001
        userId:
          type: integer
          example: 101
        addressLine1:
          type: string
          example: 123 MG Road
        addressLine2:
          type: string
          example: Apartment 4B
        city:
          type: string
          example: Bangalore
        state:
          type: string
          example: Karnataka
        zip:
          type: string
          example: 560001
        country:
          type: string
          example: India
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    AddressCreateRequest:
      type: object
      required: [addressLine1, city, state, zip, country]
      properties:
        addressLine1:
          type: string
        addressLine2:
          type: string
        city:
          type: string
        state:
          type: string
        zip:
          type: string
        country:
          type: string

    AddressUpdateRequest:
      type: object
      properties:
        addressLine1:
          type: string
        addressLine2:
          type: string
        city:
          type: string
        state:
          type: string
        zip:
          type: string
        country:
          type: string

    ShippingOption:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Standard Delivery
        estimatedDays:
          type: integer
          example: 5
        cost:
          type: number
          format: float
          example: 49.99

    Tracking:
      type: object
      properties:
        orderId:
          type: integer
          example: 5001
        status:
          type: string
          enum: [pending, dispatched, in_transit, delivered, cancelled]
          example: in_transit
        carrier:
          type: string
          example: FedEx
        trackingNumber:
          type: string
          example: FEDEX123456789
        estimatedDelivery:
          type: string
          format: date-time
          example: 2025-09-20T18:30:00Z

    ErrorResponse:
      type: object
      required: [error, message]
      properties:
        error:
          type: string
          example: NotFound
        message:
          type: string
          example: Address not found
