// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ConfirmPaymentHandlerFunc turns a function with the right signature into a confirm payment handler
type ConfirmPaymentHandlerFunc func(ConfirmPaymentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ConfirmPaymentHandlerFunc) Handle(params ConfirmPaymentParams) middleware.Responder {
	return fn(params)
}

// ConfirmPaymentHandler interface for that can handle valid confirm payment params
type ConfirmPaymentHandler interface {
	Handle(ConfirmPaymentParams) middleware.Responder
}

// NewConfirmPayment creates a new http.Handler for the confirm payment operation
func NewConfirmPayment(ctx *middleware.Context, handler ConfirmPaymentHandler) *ConfirmPayment {
	return &ConfirmPayment{Context: ctx, Handler: handler}
}

/*
	ConfirmPayment swagger:route POST /payments/{id}/confirm Payments confirmPayment

Confirm a payment
*/
type ConfirmPayment struct {
	Context *middleware.Context
	Handler ConfirmPaymentHandler
}

func (o *ConfirmPayment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewConfirmPaymentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
