// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// ConfirmPaymentOKCode is the HTTP code returned for type ConfirmPaymentOK
const ConfirmPaymentOKCode int = 200

/*
ConfirmPaymentOK Payment confirmed

swagger:response confirmPaymentOK
*/
type ConfirmPaymentOK struct {

	/*
	  In: Body
	*/
	Payload *models.Payment `json:"body,omitempty"`
}

// NewConfirmPaymentOK creates ConfirmPaymentOK with default headers values
func NewConfirmPaymentOK() *ConfirmPaymentOK {

	return &ConfirmPaymentOK{}
}

// WithPayload adds the payload to the confirm payment o k response
func (o *ConfirmPaymentOK) WithPayload(payload *models.Payment) *ConfirmPaymentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the confirm payment o k response
func (o *ConfirmPaymentOK) SetPayload(payload *models.Payment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConfirmPaymentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ConfirmPaymentBadRequestCode is the HTTP code returned for type ConfirmPaymentBadRequest
const ConfirmPaymentBadRequestCode int = 400

/*
ConfirmPaymentBadRequest Invalid confirmation data

swagger:response confirmPaymentBadRequest
*/
type ConfirmPaymentBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewConfirmPaymentBadRequest creates ConfirmPaymentBadRequest with default headers values
func NewConfirmPaymentBadRequest() *ConfirmPaymentBadRequest {

	return &ConfirmPaymentBadRequest{}
}

// WithPayload adds the payload to the confirm payment bad request response
func (o *ConfirmPaymentBadRequest) WithPayload(payload *models.ErrorResponse) *ConfirmPaymentBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the confirm payment bad request response
func (o *ConfirmPaymentBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConfirmPaymentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
