// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// InitiatePaymentCreatedCode is the HTTP code returned for type InitiatePaymentCreated
const InitiatePaymentCreatedCode int = 201

/*
InitiatePaymentCreated Payment initiated

swagger:response initiatePaymentCreated
*/
type InitiatePaymentCreated struct {

	/*
	  In: Body
	*/
	Payload *models.PaymentInitiateResponse `json:"body,omitempty"`
}

// NewInitiatePaymentCreated creates InitiatePaymentCreated with default headers values
func NewInitiatePaymentCreated() *InitiatePaymentCreated {

	return &InitiatePaymentCreated{}
}

// WithPayload adds the payload to the initiate payment created response
func (o *InitiatePaymentCreated) WithPayload(payload *models.PaymentInitiateResponse) *InitiatePaymentCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the initiate payment created response
func (o *InitiatePaymentCreated) SetPayload(payload *models.PaymentInitiateResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InitiatePaymentCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// InitiatePaymentBadRequestCode is the HTTP code returned for type InitiatePaymentBadRequest
const InitiatePaymentBadRequestCode int = 400

/*
InitiatePaymentBadRequest Invalid request

swagger:response initiatePaymentBadRequest
*/
type InitiatePaymentBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewInitiatePaymentBadRequest creates InitiatePaymentBadRequest with default headers values
func NewInitiatePaymentBadRequest() *InitiatePaymentBadRequest {

	return &InitiatePaymentBadRequest{}
}

// WithPayload adds the payload to the initiate payment bad request response
func (o *InitiatePaymentBadRequest) WithPayload(payload *models.ErrorResponse) *InitiatePaymentBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the initiate payment bad request response
func (o *InitiatePaymentBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *InitiatePaymentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
