// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"Adornme/models"
)

// InitiatePaymentHandlerFunc turns a function with the right signature into a initiate payment handler
type InitiatePaymentHandlerFunc func(InitiatePaymentParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn InitiatePaymentHandlerFunc) Handle(params InitiatePaymentParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// InitiatePaymentHandler interface for that can handle valid initiate payment params
type InitiatePaymentHandler interface {
	Handle(InitiatePaymentParams, *models.Principal) middleware.Responder
}

// NewInitiatePayment creates a new http.Handler for the initiate payment operation
func NewInitiatePayment(ctx *middleware.Context, handler InitiatePaymentHandler) *InitiatePayment {
	return &InitiatePayment{Context: ctx, Handler: handler}
}

/*
	InitiatePayment swagger:route POST /payments/initiate Payments initiatePayment

Initiate a new payment
*/
type InitiatePayment struct {
	Context *middleware.Context
	Handler InitiatePaymentHandler
}

func (o *InitiatePayment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewInitiatePaymentParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
