// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// RefundPaymentOKCode is the HTTP code returned for type RefundPaymentOK
const RefundPaymentOKCode int = 200

/*
RefundPaymentOK Refund processed

swagger:response refundPaymentOK
*/
type RefundPaymentOK struct {

	/*
	  In: Body
	*/
	Payload *models.Payment `json:"body,omitempty"`
}

// NewRefundPaymentOK creates RefundPaymentOK with default headers values
func NewRefundPaymentOK() *RefundPaymentOK {

	return &RefundPaymentOK{}
}

// WithPayload adds the payload to the refund payment o k response
func (o *RefundPaymentOK) WithPayload(payload *models.Payment) *RefundPaymentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the refund payment o k response
func (o *RefundPaymentOK) SetPayload(payload *models.Payment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RefundPaymentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RefundPaymentBadRequestCode is the HTTP code returned for type RefundPaymentBadRequest
const RefundPaymentBadRequestCode int = 400

/*
RefundPaymentBadRequest Invalid refund request

swagger:response refundPaymentBadRequest
*/
type RefundPaymentBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewRefundPaymentBadRequest creates RefundPaymentBadRequest with default headers values
func NewRefundPaymentBadRequest() *RefundPaymentBadRequest {

	return &RefundPaymentBadRequest{}
}

// WithPayload adds the payload to the refund payment bad request response
func (o *RefundPaymentBadRequest) WithPayload(payload *models.ErrorResponse) *RefundPaymentBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the refund payment bad request response
func (o *RefundPaymentBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RefundPaymentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RefundPaymentNotFoundCode is the HTTP code returned for type RefundPaymentNotFound
const RefundPaymentNotFoundCode int = 404

/*
RefundPaymentNotFound Payment not found

swagger:response refundPaymentNotFound
*/
type RefundPaymentNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewRefundPaymentNotFound creates RefundPaymentNotFound with default headers values
func NewRefundPaymentNotFound() *RefundPaymentNotFound {

	return &RefundPaymentNotFound{}
}

// WithPayload adds the payload to the refund payment not found response
func (o *RefundPaymentNotFound) WithPayload(payload *models.ErrorResponse) *RefundPaymentNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the refund payment not found response
func (o *RefundPaymentNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RefundPaymentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
