// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"Adornme/models"
)

// RefundPaymentHandlerFunc turns a function with the right signature into a refund payment handler
type RefundPaymentHandlerFunc func(RefundPaymentParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn RefundPaymentHandlerFunc) Handle(params RefundPaymentParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// RefundPaymentHandler interface for that can handle valid refund payment params
type RefundPaymentHandler interface {
	Handle(RefundPaymentParams, *models.Principal) middleware.Responder
}

// NewRefundPayment creates a new http.Handler for the refund payment operation
func NewRefundPayment(ctx *middleware.Context, handler RefundPaymentHandler) *RefundPayment {
	return &RefundPayment{Context: ctx, Handler: handler}
}

/*
	RefundPayment swagger:route POST /payments/{id}/refund Payments refundPayment

Refund a payment
*/
type RefundPayment struct {
	Context *middleware.Context
	Handler RefundPaymentHandler
}

func (o *RefundPayment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRefundPaymentParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
