// Code generated by go-swagger; DO NOT EDIT.

package cart

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteCartNoContentCode is the HTTP code returned for type DeleteCartNoContent
const DeleteCartNoContentCode int = 204

/*
DeleteCartNoContent Cart cleared

swagger:response deleteCartNoContent
*/
type DeleteCartNoContent struct {
}

// NewDeleteCartNoContent creates DeleteCartNoContent with default headers values
func NewDeleteCartNoContent() *DeleteCartNoContent {

	return &DeleteCartNoContent{}
}

// WriteResponse to the client
func (o *DeleteCartNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
