// Code generated by go-swagger; DO NOT EDIT.

package cart

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteCartHandlerFunc turns a function with the right signature into a delete cart handler
type DeleteCartHandlerFunc func(DeleteCartParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCartHandlerFunc) Handle(params DeleteCartParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteCartHandler interface for that can handle valid delete cart params
type DeleteCartHandler interface {
	Handle(DeleteCartParams, interface{}) middleware.Responder
}

// NewDeleteCart creates a new http.Handler for the delete cart operation
func NewDeleteCart(ctx *middleware.Context, handler DeleteCartHandler) *DeleteCart {
	return &DeleteCart{Context: ctx, Handler: handler}
}

/*
	DeleteCart swagger:route DELETE /cart Cart deleteCart

Clear cart
*/
type DeleteCart struct {
	Context *middleware.Context
	Handler DeleteCartHandler
}

func (o *DeleteCart) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteCartParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
