// Code generated by go-swagger; DO NOT EDIT.

package cart

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutCartHandlerFunc turns a function with the right signature into a put cart handler
type PutCartHandlerFunc func(PutCartParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutCartHandlerFunc) Handle(params PutCartParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutCartHandler interface for that can handle valid put cart params
type PutCartHandler interface {
	Handle(PutCartParams, interface{}) middleware.Responder
}

// NewPutCart creates a new http.Handler for the put cart operation
func NewPutCart(ctx *middleware.Context, handler PutCartHandler) *PutCart {
	return &PutCart{Context: ctx, Handler: handler}
}

/*
	PutCart swagger:route PUT /cart Cart putCart

Update item quantity in cart
*/
type PutCart struct {
	Context *middleware.Context
	Handler PutCartHandler
}

func (o *PutCart) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutCartParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
