// Code generated by go-swagger; DO NOT EDIT.

package cart

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/AdornmeCode/Carts/models"
)

// PutCartOKCode is the HTTP code returned for type PutCartOK
const PutCartOKCode int = 200

/*
PutCartOK Cart updated

swagger:response putCartOK
*/
type PutCartOK struct {

	/*
	  In: Body
	*/
	Payload *models.Cart `json:"body,omitempty"`
}

// NewPutCartOK creates PutCartOK with default headers values
func NewPutCartOK() *PutCartOK {

	return &PutCartOK{}
}

// WithPayload adds the payload to the put cart o k response
func (o *PutCartOK) WithPayload(payload *models.Cart) *PutCartOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put cart o k response
func (o *PutCartOK) SetPayload(payload *models.Cart) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutCartOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
