swagger: "2.0"
info:
  title: Admin API
  version: 1.0.0
  description: Admin APIs for managing products, users, orders, and payments.

host: api.adornme.com
basePath: /v1/admin
schemes:
  - https

tags:
  - name: AdminProducts
    description: Product management
  - name: AdminUsers
    description: User management
  - name: AdminOrders
    description: Order management
  - name: AdminPayments
    description: Payment/refund management

paths:
  /products:
    post:
      summary: Create a new product
      tags: [AdminProducts]
      security:
        - bearerAuth: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/ProductCreateRequest"
      responses:
        201:
          description: Product created successfully
        400:
          description: Validation error
        401:
          description: Unauthorized

  /products/{id}:
    put:
      summary: Update a product
      tags: [AdminProducts]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/ProductUpdateRequest"
      responses:
        200:
          description: Product updated
    delete:
      summary: Delete a product
      tags: [AdminProducts]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        204:
          description: Product deleted

  /users:
    get:
      summary: List all users
      tags: [AdminUsers]
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          type: integer
          default: 1
        - name: limit
          in: query
          type: integer
          default: 20
      responses:
        200:
          description: List of users

  /users/{id}:
    get:
      summary: Get user details
      tags: [AdminUsers]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: User details
    put:
      summary: Update user info
      tags: [AdminUsers]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/UserUpdateRequest"
      responses:
        200:
          description: User updated
    delete:
      summary: Delete a user
      tags: [AdminUsers]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        204:
          description: User deleted

definitions:
  ProductCreateRequest:
    type: object
    required:
      - name
      - price
      - stock
      - categoryId
    properties:
      name:
        type: string
      description:
        type: string
      price:
        type: number
        format: float
      stock:
        type: integer
      categoryId:
        type: integer
      images:
        type: array
        items:
          type: string
          format: uri

  ProductUpdateRequest:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      price:
        type: number
        format: float
      stock:
        type: integer
      categoryId:
        type: integer
      images:
        type: array
        items:
          type: string
          format: uri

  UserUpdateRequest:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
        format: email
      phone:
        type: string

securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
