// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"Adornme/AdornmeCode/Admin/restapi/operations/admin_products"
	"Adornme/AdornmeCode/Admin/restapi/operations/admin_users"
)

// NewAdornmeAPI creates a new Adornme instance
func NewAdornmeAPI(spec *loads.Document) *AdornmeAPI {
	return &AdornmeAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		AdminProductsDeleteProductsIDHandler: admin_products.DeleteProductsIDHandlerFunc(func(params admin_products.DeleteProductsIDParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation admin_products.DeleteProductsID has not yet been implemented")
		}),
		AdminUsersDeleteUsersIDHandler: admin_users.DeleteUsersIDHandlerFunc(func(params admin_users.DeleteUsersIDParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation admin_users.DeleteUsersID has not yet been implemented")
		}),
		AdminUsersGetUsersHandler: admin_users.GetUsersHandlerFunc(func(params admin_users.GetUsersParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation admin_users.GetUsers has not yet been implemented")
		}),
		AdminUsersGetUsersIDHandler: admin_users.GetUsersIDHandlerFunc(func(params admin_users.GetUsersIDParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation admin_users.GetUsersID has not yet been implemented")
		}),
		AdminProductsPostProductsHandler: admin_products.PostProductsHandlerFunc(func(params admin_products.PostProductsParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation admin_products.PostProducts has not yet been implemented")
		}),
		AdminProductsPutProductsIDHandler: admin_products.PutProductsIDHandlerFunc(func(params admin_products.PutProductsIDParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation admin_products.PutProductsID has not yet been implemented")
		}),
		AdminUsersPutUsersIDHandler: admin_users.PutUsersIDHandlerFunc(func(params admin_users.PutUsersIDParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation admin_users.PutUsersID has not yet been implemented")
		}),

		// Applies when the "Authorization" header is set
		BearerAuthAuth: func(token string) (interface{}, error) {
			return nil, errors.NotImplemented("api key auth (bearerAuth) Authorization from header param [Authorization] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*AdornmeAPI Admin APIs for managing products, users, orders, and payments. */
type AdornmeAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// BearerAuthAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Authorization provided in the header
	BearerAuthAuth func(string) (interface{}, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// AdminProductsDeleteProductsIDHandler sets the operation handler for the delete products ID operation
	AdminProductsDeleteProductsIDHandler admin_products.DeleteProductsIDHandler
	// AdminUsersDeleteUsersIDHandler sets the operation handler for the delete users ID operation
	AdminUsersDeleteUsersIDHandler admin_users.DeleteUsersIDHandler
	// AdminUsersGetUsersHandler sets the operation handler for the get users operation
	AdminUsersGetUsersHandler admin_users.GetUsersHandler
	// AdminUsersGetUsersIDHandler sets the operation handler for the get users ID operation
	AdminUsersGetUsersIDHandler admin_users.GetUsersIDHandler
	// AdminProductsPostProductsHandler sets the operation handler for the post products operation
	AdminProductsPostProductsHandler admin_products.PostProductsHandler
	// AdminProductsPutProductsIDHandler sets the operation handler for the put products ID operation
	AdminProductsPutProductsIDHandler admin_products.PutProductsIDHandler
	// AdminUsersPutUsersIDHandler sets the operation handler for the put users ID operation
	AdminUsersPutUsersIDHandler admin_users.PutUsersIDHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *AdornmeAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *AdornmeAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *AdornmeAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *AdornmeAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *AdornmeAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *AdornmeAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *AdornmeAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *AdornmeAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *AdornmeAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the AdornmeAPI
func (o *AdornmeAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BearerAuthAuth == nil {
		unregistered = append(unregistered, "AuthorizationAuth")
	}

	if o.AdminProductsDeleteProductsIDHandler == nil {
		unregistered = append(unregistered, "admin_products.DeleteProductsIDHandler")
	}
	if o.AdminUsersDeleteUsersIDHandler == nil {
		unregistered = append(unregistered, "admin_users.DeleteUsersIDHandler")
	}
	if o.AdminUsersGetUsersHandler == nil {
		unregistered = append(unregistered, "admin_users.GetUsersHandler")
	}
	if o.AdminUsersGetUsersIDHandler == nil {
		unregistered = append(unregistered, "admin_users.GetUsersIDHandler")
	}
	if o.AdminProductsPostProductsHandler == nil {
		unregistered = append(unregistered, "admin_products.PostProductsHandler")
	}
	if o.AdminProductsPutProductsIDHandler == nil {
		unregistered = append(unregistered, "admin_products.PutProductsIDHandler")
	}
	if o.AdminUsersPutUsersIDHandler == nil {
		unregistered = append(unregistered, "admin_users.PutUsersIDHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *AdornmeAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *AdornmeAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "bearerAuth":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, o.BearerAuthAuth)

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *AdornmeAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *AdornmeAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *AdornmeAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *AdornmeAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the adornme API
func (o *AdornmeAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *AdornmeAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/products/{id}"] = admin_products.NewDeleteProductsID(o.context, o.AdminProductsDeleteProductsIDHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/users/{id}"] = admin_users.NewDeleteUsersID(o.context, o.AdminUsersDeleteUsersIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users"] = admin_users.NewGetUsers(o.context, o.AdminUsersGetUsersHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users/{id}"] = admin_users.NewGetUsersID(o.context, o.AdminUsersGetUsersIDHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/products"] = admin_products.NewPostProducts(o.context, o.AdminProductsPostProductsHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/products/{id}"] = admin_products.NewPutProductsID(o.context, o.AdminProductsPutProductsIDHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/users/{id}"] = admin_users.NewPutUsersID(o.context, o.AdminUsersPutUsersIDHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *AdornmeAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *AdornmeAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *AdornmeAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *AdornmeAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *AdornmeAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
