// Code generated by go-swagger; DO NOT EDIT.

package shipping

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"Adornme/models"
)

// AddShippingAddressHandlerFunc turns a function with the right signature into a add shipping address handler
type AddShippingAddressHandlerFunc func(AddShippingAddressParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn AddShippingAddressHandlerFunc) Handle(params AddShippingAddressParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// AddShippingAddressHandler interface for that can handle valid add shipping address params
type AddShippingAddressHandler interface {
	Handle(AddShippingAddressParams, *models.Principal) middleware.Responder
}

// NewAddShippingAddress creates a new http.Handler for the add shipping address operation
func NewAddShippingAddress(ctx *middleware.Context, handler AddShippingAddressHandler) *AddShippingAddress {
	return &AddShippingAddress{Context: ctx, Handler: handler}
}

/*
	AddShippingAddress swagger:route POST /shipping/addresses Shipping addShippingAddress

Add a new shipping address
*/
type AddShippingAddress struct {
	Context *middleware.Context
	Handler AddShippingAddressHandler
}

func (o *AddShippingAddress) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddShippingAddressParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
