// Code generated by go-swagger; DO NOT EDIT.

package shipping

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// DeleteShippingAddressNoContentCode is the HTTP code returned for type DeleteShippingAddressNoContent
const DeleteShippingAddressNoContentCode int = 204

/*
DeleteShippingAddressNoContent Address deleted

swagger:response deleteShippingAddressNoContent
*/
type DeleteShippingAddressNoContent struct {
}

// NewDeleteShippingAddressNoContent creates DeleteShippingAddressNoContent with default headers values
func NewDeleteShippingAddressNoContent() *DeleteShippingAddressNoContent {

	return &DeleteShippingAddressNoContent{}
}

// WriteResponse to the client
func (o *DeleteShippingAddressNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteShippingAddressNotFoundCode is the HTTP code returned for type DeleteShippingAddressNotFound
const DeleteShippingAddressNotFoundCode int = 404

/*
DeleteShippingAddressNotFound Address not found

swagger:response deleteShippingAddressNotFound
*/
type DeleteShippingAddressNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewDeleteShippingAddressNotFound creates DeleteShippingAddressNotFound with default headers values
func NewDeleteShippingAddressNotFound() *DeleteShippingAddressNotFound {

	return &DeleteShippingAddressNotFound{}
}

// WithPayload adds the payload to the delete shipping address not found response
func (o *DeleteShippingAddressNotFound) WithPayload(payload *models.ErrorResponse) *DeleteShippingAddressNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete shipping address not found response
func (o *DeleteShippingAddressNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteShippingAddressNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
