// Code generated by go-swagger; DO NOT EDIT.

package shipping

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// ListShippingOptionsOKCode is the HTTP code returned for type ListShippingOptionsOK
const ListShippingOptionsOKCode int = 200

/*
ListShippingOptionsOK List of shipping options

swagger:response listShippingOptionsOK
*/
type ListShippingOptionsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ShippingOption `json:"body,omitempty"`
}

// NewListShippingOptionsOK creates ListShippingOptionsOK with default headers values
func NewListShippingOptionsOK() *ListShippingOptionsOK {

	return &ListShippingOptionsOK{}
}

// WithPayload adds the payload to the list shipping options o k response
func (o *ListShippingOptionsOK) WithPayload(payload []*models.ShippingOption) *ListShippingOptionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list shipping options o k response
func (o *ListShippingOptionsOK) SetPayload(payload []*models.ShippingOption) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListShippingOptionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ShippingOption, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
