// Code generated by go-swagger; DO NOT EDIT.

package shipping

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListShippingOptionsHandlerFunc turns a function with the right signature into a list shipping options handler
type ListShippingOptionsHandlerFunc func(ListShippingOptionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListShippingOptionsHandlerFunc) Handle(params ListShippingOptionsParams) middleware.Responder {
	return fn(params)
}

// ListShippingOptionsHandler interface for that can handle valid list shipping options params
type ListShippingOptionsHandler interface {
	Handle(ListShippingOptionsParams) middleware.Responder
}

// NewListShippingOptions creates a new http.Handler for the list shipping options operation
func NewListShippingOptions(ctx *middleware.Context, handler ListShippingOptionsHandler) *ListShippingOptions {
	return &ListShippingOptions{Context: ctx, Handler: handler}
}

/*
	ListShippingOptions swagger:route GET /shipping/options Shipping listShippingOptions

Get available shipping options
*/
type ListShippingOptions struct {
	Context *middleware.Context
	Handler ListShippingOptionsHandler
}

func (o *ListShippingOptions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListShippingOptionsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
