// Code generated by go-swagger; DO NOT EDIT.

package shipping

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"Adornme/models"
)

// ListShippingAddressesHandlerFunc turns a function with the right signature into a list shipping addresses handler
type ListShippingAddressesHandlerFunc func(ListShippingAddressesParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ListShippingAddressesHandlerFunc) Handle(params ListShippingAddressesParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// ListShippingAddressesHandler interface for that can handle valid list shipping addresses params
type ListShippingAddressesHandler interface {
	Handle(ListShippingAddressesParams, *models.Principal) middleware.Responder
}

// NewListShippingAddresses creates a new http.Handler for the list shipping addresses operation
func NewListShippingAddresses(ctx *middleware.Context, handler ListShippingAddressesHandler) *ListShippingAddresses {
	return &ListShippingAddresses{Context: ctx, Handler: handler}
}

/*
	ListShippingAddresses swagger:route GET /shipping/addresses Shipping listShippingAddresses

Get all addresses for logged-in user
*/
type ListShippingAddresses struct {
	Context *middleware.Context
	Handler ListShippingAddressesHandler
}

func (o *ListShippingAddresses) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListShippingAddressesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
