// Code generated by go-swagger; DO NOT EDIT.

package shipping

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// ListShippingAddressesOKCode is the HTTP code returned for type ListShippingAddressesOK
const ListShippingAddressesOKCode int = 200

/*
ListShippingAddressesOK List of user addresses

swagger:response listShippingAddressesOK
*/
type ListShippingAddressesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Address `json:"body,omitempty"`
}

// NewListShippingAddressesOK creates ListShippingAddressesOK with default headers values
func NewListShippingAddressesOK() *ListShippingAddressesOK {

	return &ListShippingAddressesOK{}
}

// WithPayload adds the payload to the list shipping addresses o k response
func (o *ListShippingAddressesOK) WithPayload(payload []*models.Address) *ListShippingAddressesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list shipping addresses o k response
func (o *ListShippingAddressesOK) SetPayload(payload []*models.Address) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListShippingAddressesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Address, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListShippingAddressesUnauthorizedCode is the HTTP code returned for type ListShippingAddressesUnauthorized
const ListShippingAddressesUnauthorizedCode int = 401

/*
ListShippingAddressesUnauthorized Unauthorized

swagger:response listShippingAddressesUnauthorized
*/
type ListShippingAddressesUnauthorized struct {
}

// NewListShippingAddressesUnauthorized creates ListShippingAddressesUnauthorized with default headers values
func NewListShippingAddressesUnauthorized() *ListShippingAddressesUnauthorized {

	return &ListShippingAddressesUnauthorized{}
}

// WriteResponse to the client
func (o *ListShippingAddressesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
