// Code generated by go-swagger; DO NOT EDIT.

package shipping

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// TrackShipmentOKCode is the HTTP code returned for type TrackShipmentOK
const TrackShipmentOKCode int = 200

/*
TrackShipmentOK Shipment tracking details

swagger:response trackShipmentOK
*/
type TrackShipmentOK struct {

	/*
	  In: Body
	*/
	Payload *models.Tracking `json:"body,omitempty"`
}

// NewTrackShipmentOK creates TrackShipmentOK with default headers values
func NewTrackShipmentOK() *TrackShipmentOK {

	return &TrackShipmentOK{}
}

// WithPayload adds the payload to the track shipment o k response
func (o *TrackShipmentOK) WithPayload(payload *models.Tracking) *TrackShipmentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the track shipment o k response
func (o *TrackShipmentOK) SetPayload(payload *models.Tracking) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TrackShipmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// TrackShipmentNotFoundCode is the HTTP code returned for type TrackShipmentNotFound
const TrackShipmentNotFoundCode int = 404

/*
TrackShipmentNotFound Order or shipment not found

swagger:response trackShipmentNotFound
*/
type TrackShipmentNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewTrackShipmentNotFound creates TrackShipmentNotFound with default headers values
func NewTrackShipmentNotFound() *TrackShipmentNotFound {

	return &TrackShipmentNotFound{}
}

// WithPayload adds the payload to the track shipment not found response
func (o *TrackShipmentNotFound) WithPayload(payload *models.ErrorResponse) *TrackShipmentNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the track shipment not found response
func (o *TrackShipmentNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TrackShipmentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
