// Code generated by go-swagger; DO NOT EDIT.

package shipping

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"Adornme/models"
)

// UpdateShippingAddressHandlerFunc turns a function with the right signature into a update shipping address handler
type UpdateShippingAddressHandlerFunc func(UpdateShippingAddressParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateShippingAddressHandlerFunc) Handle(params UpdateShippingAddressParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateShippingAddressHandler interface for that can handle valid update shipping address params
type UpdateShippingAddressHandler interface {
	Handle(UpdateShippingAddressParams, *models.Principal) middleware.Responder
}

// NewUpdateShippingAddress creates a new http.Handler for the update shipping address operation
func NewUpdateShippingAddress(ctx *middleware.Context, handler UpdateShippingAddressHandler) *UpdateShippingAddress {
	return &UpdateShippingAddress{Context: ctx, Handler: handler}
}

/*
	UpdateShippingAddress swagger:route PUT /shipping/addresses/{id} Shipping updateShippingAddress

Update a shipping address
*/
type UpdateShippingAddress struct {
	Context *middleware.Context
	Handler UpdateShippingAddressHandler
}

func (o *UpdateShippingAddress) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateShippingAddressParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
