// Code generated by go-swagger; DO NOT EDIT.

package shipping

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Adornme/models"
)

// UpdateShippingAddressOKCode is the HTTP code returned for type UpdateShippingAddressOK
const UpdateShippingAddressOKCode int = 200

/*
UpdateShippingAddressOK Address updated

swagger:response updateShippingAddressOK
*/
type UpdateShippingAddressOK struct {

	/*
	  In: Body
	*/
	Payload *models.Address `json:"body,omitempty"`
}

// NewUpdateShippingAddressOK creates UpdateShippingAddressOK with default headers values
func NewUpdateShippingAddressOK() *UpdateShippingAddressOK {

	return &UpdateShippingAddressOK{}
}

// WithPayload adds the payload to the update shipping address o k response
func (o *UpdateShippingAddressOK) WithPayload(payload *models.Address) *UpdateShippingAddressOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update shipping address o k response
func (o *UpdateShippingAddressOK) SetPayload(payload *models.Address) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateShippingAddressOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateShippingAddressNotFoundCode is the HTTP code returned for type UpdateShippingAddressNotFound
const UpdateShippingAddressNotFoundCode int = 404

/*
UpdateShippingAddressNotFound Address not found

swagger:response updateShippingAddressNotFound
*/
type UpdateShippingAddressNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewUpdateShippingAddressNotFound creates UpdateShippingAddressNotFound with default headers values
func NewUpdateShippingAddressNotFound() *UpdateShippingAddressNotFound {

	return &UpdateShippingAddressNotFound{}
}

// WithPayload adds the payload to the update shipping address not found response
func (o *UpdateShippingAddressNotFound) WithPayload(payload *models.ErrorResponse) *UpdateShippingAddressNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update shipping address not found response
func (o *UpdateShippingAddressNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateShippingAddressNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
