// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddressUpdateRequest Payload to update an existing address.
//
// swagger:model AddressUpdateRequest
type AddressUpdateRequest struct {

	// address line1
	AddressLine1 string `json:"addressLine1,omitempty"`

	// address line2
	AddressLine2 string `json:"addressLine2,omitempty"`

	// city
	City string `json:"city,omitempty"`

	// country
	Country string `json:"country,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// zip
	Zip string `json:"zip,omitempty"`
}

// Validate validates this address update request
func (m *AddressUpdateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this address update request based on context it is used
func (m *AddressUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddressUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddressUpdateRequest) UnmarshalBinary(b []byte) error {
	var res AddressUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
