// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrderCreateRequest Request to create a new order.
//
// swagger:model OrderCreateRequest
type OrderCreateRequest struct {

	// payment method
	// Example: upi
	// Required: true
	// Enum: [cod card netbanking upi]
	PaymentMethod *string `json:"paymentMethod"`

	// shipping address Id
	// Example: 2001
	// Required: true
	ShippingAddressID *int64 `json:"shippingAddressId"`
}

// Validate validates this order create request
func (m *OrderCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePaymentMethod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateShippingAddressID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var orderCreateRequestTypePaymentMethodPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["cod","card","netbanking","upi"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		orderCreateRequestTypePaymentMethodPropEnum = append(orderCreateRequestTypePaymentMethodPropEnum, v)
	}
}

const (

	// OrderCreateRequestPaymentMethodCod captures enum value "cod"
	OrderCreateRequestPaymentMethodCod string = "cod"

	// OrderCreateRequestPaymentMethodCard captures enum value "card"
	OrderCreateRequestPaymentMethodCard string = "card"

	// OrderCreateRequestPaymentMethodNetbanking captures enum value "netbanking"
	OrderCreateRequestPaymentMethodNetbanking string = "netbanking"

	// OrderCreateRequestPaymentMethodUpi captures enum value "upi"
	OrderCreateRequestPaymentMethodUpi string = "upi"
)

// prop value enum
func (m *OrderCreateRequest) validatePaymentMethodEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, orderCreateRequestTypePaymentMethodPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *OrderCreateRequest) validatePaymentMethod(formats strfmt.Registry) error {

	if err := validate.Required("paymentMethod", "body", m.PaymentMethod); err != nil {
		return err
	}

	// value enum
	if err := m.validatePaymentMethodEnum("paymentMethod", "body", *m.PaymentMethod); err != nil {
		return err
	}

	return nil
}

func (m *OrderCreateRequest) validateShippingAddressID(formats strfmt.Registry) error {

	if err := validate.Required("shippingAddressId", "body", m.ShippingAddressID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this order create request based on context it is used
func (m *OrderCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderCreateRequest) UnmarshalBinary(b []byte) error {
	var res OrderCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
