// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaymentInitiateResponse Response after payment initiation.
//
// swagger:model PaymentInitiateResponse
type PaymentInitiateResponse struct {

	// gateway Url
	GatewayURL string `json:"gatewayUrl,omitempty"`

	// payment Id
	PaymentID string `json:"paymentId,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this payment initiate response
func (m *PaymentInitiateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this payment initiate response based on context it is used
func (m *PaymentInitiateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaymentInitiateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentInitiateResponse) UnmarshalBinary(b []byte) error {
	var res PaymentInitiateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
