// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProductCreateRequest Request to create a new product.
//
// swagger:model ProductCreateRequest
type ProductCreateRequest struct {

	// category Id
	// Required: true
	CategoryID *int64 `json:"categoryId"`

	// description
	Description string `json:"description,omitempty"`

	// images
	Images []string `json:"images"`

	// name
	// Required: true
	Name *string `json:"name"`

	// price
	// Required: true
	Price *float32 `json:"price"`

	// stock
	// Required: true
	Stock *int64 `json:"stock"`
}

// Validate validates this product create request
func (m *ProductCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCategoryID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStock(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProductCreateRequest) validateCategoryID(formats strfmt.Registry) error {

	if err := validate.Required("categoryId", "body", m.CategoryID); err != nil {
		return err
	}

	return nil
}

func (m *ProductCreateRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *ProductCreateRequest) validatePrice(formats strfmt.Registry) error {

	if err := validate.Required("price", "body", m.Price); err != nil {
		return err
	}

	return nil
}

func (m *ProductCreateRequest) validateStock(formats strfmt.Registry) error {

	if err := validate.Required("stock", "body", m.Stock); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this product create request based on context it is used
func (m *ProductCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProductCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProductCreateRequest) UnmarshalBinary(b []byte) error {
	var res ProductCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
