// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RefreshTokenRequest Payload to refresh authentication token.
//
// swagger:model RefreshTokenRequest
type RefreshTokenRequest struct {

	// refresh token
	// Example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
	// Required: true
	RefreshToken *string `json:"refreshToken"`
}

// Validate validates this refresh token request
func (m *RefreshTokenRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRefreshToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RefreshTokenRequest) validateRefreshToken(formats strfmt.Registry) error {

	if err := validate.Required("refreshToken", "body", m.RefreshToken); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this refresh token request based on context it is used
func (m *RefreshTokenRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RefreshTokenRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RefreshTokenRequest) UnmarshalBinary(b []byte) error {
	var res RefreshTokenRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
