// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Tracking Represents order tracking details.
//
// swagger:model Tracking
type Tracking struct {

	// carrier
	Carrier string `json:"carrier,omitempty"`

	// estimated delivery
	// Format: date-time
	EstimatedDelivery strfmt.DateTime `json:"estimatedDelivery,omitempty"`

	// order Id
	OrderID int64 `json:"orderId,omitempty"`

	// status
	// Enum: [pending dispatched in_transit delivered cancelled]
	Status string `json:"status,omitempty"`

	// tracking number
	TrackingNumber string `json:"trackingNumber,omitempty"`
}

// Validate validates this tracking
func (m *Tracking) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEstimatedDelivery(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Tracking) validateEstimatedDelivery(formats strfmt.Registry) error {
	if swag.IsZero(m.EstimatedDelivery) { // not required
		return nil
	}

	if err := validate.FormatOf("estimatedDelivery", "body", "date-time", m.EstimatedDelivery.String(), formats); err != nil {
		return err
	}

	return nil
}

var trackingTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["pending","dispatched","in_transit","delivered","cancelled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		trackingTypeStatusPropEnum = append(trackingTypeStatusPropEnum, v)
	}
}

const (

	// TrackingStatusPending captures enum value "pending"
	TrackingStatusPending string = "pending"

	// TrackingStatusDispatched captures enum value "dispatched"
	TrackingStatusDispatched string = "dispatched"

	// TrackingStatusInTransit captures enum value "in_transit"
	TrackingStatusInTransit string = "in_transit"

	// TrackingStatusDelivered captures enum value "delivered"
	TrackingStatusDelivered string = "delivered"

	// TrackingStatusCancelled captures enum value "cancelled"
	TrackingStatusCancelled string = "cancelled"
)

// prop value enum
func (m *Tracking) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, trackingTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Tracking) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this tracking based on context it is used
func (m *Tracking) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Tracking) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Tracking) UnmarshalBinary(b []byte) error {
	var res Tracking
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
