// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VerifyOTPResponse verify o t p response
//
// swagger:model VerifyOTPResponse
type VerifyOTPResponse struct {

	// message
	// Example: Login successful
	Message string `json:"message,omitempty"`

	// token
	// Example: jwt-token-here
	Token string `json:"token,omitempty"`
}

// Validate validates this verify o t p response
func (m *VerifyOTPResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this verify o t p response based on context it is used
func (m *VerifyOTPResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VerifyOTPResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VerifyOTPResponse) UnmarshalBinary(b []byte) error {
	var res VerifyOTPResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
