// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VerifyOTPRequest verify o t p request
//
// swagger:model VerifyOTPRequest
type VerifyOTPRequest struct {

	// identifier
	// Example: +919968177234
	// Required: true
	Identifier *string `json:"identifier"`

	// otp
	// Example: 123456
	// Required: true
	Otp *string `json:"otp"`
}

// Validate validates this verify o t p request
func (m *VerifyOTPRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIdentifier(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOtp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VerifyOTPRequest) validateIdentifier(formats strfmt.Registry) error {

	if err := validate.Required("identifier", "body", m.Identifier); err != nil {
		return err
	}

	return nil
}

func (m *VerifyOTPRequest) validateOtp(formats strfmt.Registry) error {

	if err := validate.Required("otp", "body", m.Otp); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this verify o t p request based on context it is used
func (m *VerifyOTPRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VerifyOTPRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VerifyOTPRequest) UnmarshalBinary(b []byte) error {
	var res VerifyOTPRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
