swagger: "2.0"
info:
  title: Product API
  version: 1.0.0
  description: >
    API specification for managing products in the e-commerce system.
    This API is used by the customer-facing side of the application.

host: api.adornme.com
basePath: /v1
schemes:
  - https

tags:
  - name: Products
    description: Operations related to products

paths:
  /products:
    get:
      summary: List products
      tags:
        - Products
      parameters:
        - name: page
          in: query
          type: integer
          default: 1
          description: Page number
        - name: limit
          in: query
          type: integer
          default: 20
          description: Number of items per page
        - name: search
          in: query
          type: string
          description: Search term to filter products
        - name: categoryId
          in: query
          type: integer
          description: Filter products by category ID
      responses:
        200:
          description: A paginated list of products
          schema:
            $ref: "#/definitions/ProductListResponse"
        400:
          description: Invalid query parameters
          schema:
            $ref: "#/definitions/ErrorResponse"

    post:
      summary: Create a new product (Admin only)
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/ProductCreateRequest"
      responses:
        201:
          description: Product created successfully
          schema:
            $ref: "#/definitions/Product"
        400:
          description: Validation error
          schema:
            $ref: "#/definitions/ErrorResponse"
        401:
          description: Unauthorized

  /products/{id}:
    get:
      summary: Get product by ID
      tags:
        - Products
      parameters:
        - in: path
          name: id
          type: integer
          required: true
      responses:
        200:
          description: Product details
          schema:
            $ref: "#/definitions/Product"
        404:
          description: Product not found
          schema:
            $ref: "#/definitions/ErrorResponse"

    put:
      summary: Update a product (Admin only)
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          type: integer
          required: true
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/ProductUpdateRequest"
      responses:
        200:
          description: Product updated successfully
          schema:
            $ref: "#/definitions/Product"
        400:
          description: Validation error
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: Product not found
          schema:
            $ref: "#/definitions/ErrorResponse"

    delete:
      summary: Delete a product (Admin only)
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          type: integer
          required: true
      responses:
        204:
          description: Product deleted successfully
        404:
          description: Product not found
          schema:
            $ref: "#/definitions/ErrorResponse"

securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Product:
    type: object
    required:
      - id
      - name
      - price
      - stock
      - categoryId
    properties:
      id:
        type: integer
        example: 101
      name:
        type: string
        example: Gold Necklace
      description:
        type: string
        example: 22K pure gold necklace with intricate design
      price:
        type: number
        format: float
        example: 14999.99
      stock:
        type: integer
        example: 20
      categoryId:
        type: integer
        example: 5
      images:
        type: array
        items:
          type: string
        example:
          - https://cdn.adornme.com/products/101-1.jpg
          - https://cdn.adornme.com/products/101-2.jpg
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time

  ProductCreateRequest:
    type: object
    required:
      - name
      - price
      - stock
      - categoryId
    properties:
      name:
        type: string
      description:
        type: string
      price:
        type: number
        format: float
      stock:
        type: integer
      categoryId:
        type: integer
      images:
        type: array
        items:
          type: string

  ProductUpdateRequest:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      price:
        type: number
        format: float
      stock:
        type: integer
      categoryId:
        type: integer
      images:
        type: array
        items:
          type: string

  ProductListResponse:
    type: object
    properties:
      page:
        type: integer
        example: 1
      limit:
        type: integer
        example: 20
      total:
        type: integer
        example: 100
      items:
        type: array
        items:
          $ref: "#/definitions/Product"

  ErrorResponse:
    type: object
    required:
      - error
      - message
    properties:
      error:
        type: string
        example: BadRequest
      message:
        type: string
        example: Invalid request parameters
